2021-07-31 22:31:33.001 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb1cd381378>
    └ <Thread(Thread-547, started daemon 140401355167488)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb1cd381158>
    └ <Thread(Thread-547, started daemon 140401355167488)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-547, started daemon 140401355167488)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-547, started daemon 140401355167488)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>>
    └ <Thread(Thread-547, started daemon 140401355167488)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 65420)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb1c6f38e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │    │                   │        └ ('127.0.0.1', 65420)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb1c5fe4b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd7b3278>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb1c5fe4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd7b3278>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb1c5fe40d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd7b3278>
    │       └ <function BaseHandler.run at 0x7fb1c5fdbd90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1be34ec88>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb1c5fe1158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1be34ec88>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1be34ec88>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1be34ec88>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │    └ <function BaseHandler.get_response at 0x7fb1c616b840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-23/doc-70/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf2f0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf730>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf7b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf840>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf29cf28>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               │    └ <function BaseHandler._get_response at 0x7fb1bf29c730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 23, 'doc_id': 70}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-23/doc-70/'>
               └ <function doc at 0x7fb1c4036048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 23, 'doc_id': 70}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-23/doc-70/'>
           └ <function doc at 0x7fb1c4033f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 70
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fb1c60f5048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 70, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fb1c70008c8>
                   └ <django.db.models.manager.Manager object at 0x7fb1bf35a208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-01 03:10:21.620 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb1cd381378>
    └ <Thread(Thread-617, started daemon 140401355167488)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb1cd381158>
    └ <Thread(Thread-617, started daemon 140401355167488)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-617, started daemon 140401355167488)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-617, started daemon 140401355167488)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>>
    └ <Thread(Thread-617, started daemon 140401355167488)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 1354)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb1c6f38e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │    │                   │        └ ('127.0.0.1', 1354)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb1c5fe4b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd740128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb1c5fe4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd740128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb1c5fe40d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd740128>
    │       └ <function BaseHandler.run at 0x7fb1c5fdbd90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1be276ac8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb1c5fe1158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1be276ac8>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1be276ac8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1be276ac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               │    └ <function BaseHandler.get_response at 0x7fb1c616b840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-152/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf2f0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf730>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf7b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf840>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf29cf28>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               │    └ <function BaseHandler._get_response at 0x7fb1bf29c730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-152/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 152}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-152/'>
               └ <function doc at 0x7fb1c4036048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 152}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-152/'>
           └ <function doc at 0x7fb1c4033f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 152
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fb1c60f5048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 152, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fb1c70008c8>
                   └ <django.db.models.manager.Manager object at 0x7fb1bf35a208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-01 09:49:38.875 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb1cd381378>
    └ <Thread(Thread-730, started daemon 140401363560192)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb1cd381158>
    └ <Thread(Thread-730, started daemon 140401363560192)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-730, started daemon 140401363560192)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-730, started daemon 140401363560192)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>>
    └ <Thread(Thread-730, started daemon 140401363560192)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 2028)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb1c6f38e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │    │                   │        └ ('127.0.0.1', 2028)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb1c5fe4b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1be27b518>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb1c5fe4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1be27b518>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb1c5fe40d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1be27b518>
    │       └ <function BaseHandler.run at 0x7fb1c5fdbd90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd8b6e10>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb1c5fe1158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd8b6e10>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd8b6e10>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd8b6e10>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │    └ <function BaseHandler.get_response at 0x7fb1c616b840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-510/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf2f0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf730>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf7b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf840>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf29cf28>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │    └ <function BaseHandler._get_response at 0x7fb1bf29c730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 510}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <function doc at 0x7fb1c4036048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 510}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-510/'>
           └ <function doc at 0x7fb1c4033f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 510
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fb1c60f5048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 510, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fb1c70008c8>
                   └ <django.db.models.manager.Manager object at 0x7fb1bf35a208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-01 09:58:39.465 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb1cd381378>
    └ <Thread(Thread-738, started daemon 140401363560192)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb1cd381158>
    └ <Thread(Thread-738, started daemon 140401363560192)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-738, started daemon 140401363560192)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-738, started daemon 140401363560192)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>>
    └ <Thread(Thread-738, started daemon 140401363560192)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 2052)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb1c6f38e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │    │                   │        └ ('127.0.0.1', 2052)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb1c5fe4b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd9c52b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb1c5fe4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd9c52b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb1c5fe40d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd9c52b0>
    │       └ <function BaseHandler.run at 0x7fb1c5fdbd90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd8b6048>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb1c5fe1158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd8b6048>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd8b6048>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd8b6048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │    └ <function BaseHandler.get_response at 0x7fb1c616b840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-52/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf2f0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf730>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf7b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf840>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf29cf28>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │    └ <function BaseHandler._get_response at 0x7fb1bf29c730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 52}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <function doc at 0x7fb1c4036048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 52}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-52/'>
           └ <function doc at 0x7fb1c4033f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 52
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fb1c60f5048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 52, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fb1c70008c8>
                   └ <django.db.models.manager.Manager object at 0x7fb1bf35a208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-01 12:50:56.772 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb1cd381378>
    └ <Thread(Thread-794, started daemon 140401138726656)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb1cd381158>
    └ <Thread(Thread-794, started daemon 140401138726656)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-794, started daemon 140401138726656)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-794, started daemon 140401138726656)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>>
    └ <Thread(Thread-794, started daemon 140401138726656)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 2374)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb1c6f38e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │    │                   │        └ ('127.0.0.1', 2374)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb1c5fe4b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd8ffe80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb1c5fe4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd8ffe80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb1c5fe40d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd8ffe80>
    │       └ <function BaseHandler.run at 0x7fb1c5fdbd90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bc5cc550>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb1c5fe1158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bc5cc550>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bc5cc550>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bc5cc550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler.get_response at 0x7fb1c616b840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf2f0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf730>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf7b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf840>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf29cf28>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler._get_response at 0x7fb1bf29c730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 53}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <function doc at 0x7fb1c4036048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 53}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-53/'>
           └ <function doc at 0x7fb1c4033f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 53
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fb1c60f5048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 53, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fb1c70008c8>
                   └ <django.db.models.manager.Manager object at 0x7fb1bf35a208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-01 13:20:56.838 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb1cd381378>
    └ <Thread(Thread-798, started daemon 140401138726656)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb1cd381158>
    └ <Thread(Thread-798, started daemon 140401138726656)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-798, started daemon 140401138726656)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-798, started daemon 140401138726656)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>>
    └ <Thread(Thread-798, started daemon 140401138726656)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 2412)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb1c6f38e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │    │                   │        └ ('127.0.0.1', 2412)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb1c5fe4b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd7baef0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb1c5fe4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd7baef0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb1c5fe40d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bd7baef0>
    │       └ <function BaseHandler.run at 0x7fb1c5fdbd90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd66cda0>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb1c5fe1158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd66cda0>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd66cda0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd66cda0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │    └ <function BaseHandler.get_response at 0x7fb1c616b840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-52/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf2f0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf730>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf7b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf840>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf29cf28>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │    └ <function BaseHandler._get_response at 0x7fb1bf29c730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 52}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <function doc at 0x7fb1c4036048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 52}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-52/'>
           └ <function doc at 0x7fb1c4033f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 52
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fb1c60f5048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 52, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fb1c70008c8>
                   └ <django.db.models.manager.Manager object at 0x7fb1bf35a208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-01 13:50:57.793 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb1cd381378>
    └ <Thread(Thread-799, started daemon 140401138726656)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb1cd381158>
    └ <Thread(Thread-799, started daemon 140401138726656)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-799, started daemon 140401138726656)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-799, started daemon 140401138726656)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>>
    └ <Thread(Thread-799, started daemon 140401138726656)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 2480)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb1c6f38e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │    │                   │        └ ('127.0.0.1', 2480)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb1c5fe4b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1be276ac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb1c5fe4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1be276ac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb1c5fe40d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1be276ac8>
    │       └ <function BaseHandler.run at 0x7fb1c5fdbd90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd783ba8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb1c5fe1158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd783ba8>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd783ba8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd783ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function BaseHandler.get_response at 0x7fb1c616b840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf2f0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf730>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf7b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf840>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf29cf28>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function BaseHandler._get_response at 0x7fb1bf29c730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 161}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <function doc at 0x7fb1c4036048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 161}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-161/'>
           └ <function doc at 0x7fb1c4033f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 161
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fb1c60f5048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 161, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fb1c70008c8>
                   └ <django.db.models.manager.Manager object at 0x7fb1bf35a208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-01 14:29:37.554 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-31_1508100.8334154685442979.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-31_1508100.8334154685442979.png?",)
2021-08-01 14:29:37.616 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-31_1540400.9407862051207854.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-31_1540400.9407862051207854.png?",)
2021-08-01 14:29:37.627 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-31_145630.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-31_145630.png?",)
2021-08-01 14:29:37.650 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_0931150.3235706871602445.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_0931150.3235706871602445.png?",)
2021-08-01 14:29:37.666 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-31_143453.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-31_143453.png?",)
2021-08-01 14:56:36.701 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-31_1508100.8334154685442979.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-31_1508100.8334154685442979.png?",)
2021-08-01 14:56:36.720 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-31_145630.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-31_145630.png?",)
2021-08-01 14:56:36.739 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-31_143453.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-31_143453.png?",)
2021-08-01 14:56:36.756 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_0931150.3235706871602445.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_0931150.3235706871602445.png?",)
2021-08-01 14:56:36.775 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1429370.555284820987625.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1429370.555284820987625.png?",)
2021-08-01 14:56:36.791 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202107/2021-07-31_1540400.9407862051207854.png': No schema supplied. Perhaps you meant http:///media/202107/2021-07-31_1540400.9407862051207854.png?",)
2021-08-01 14:56:36.810 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1429370.19590741152196445.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1429370.19590741152196445.png?",)
