2021-08-28 13:39:44.074 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f5f3f08f378>
    └ <Thread(Thread-570, started daemon 140046784157440)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f5f3f08f158>
    └ <Thread(Thread-570, started daemon 140046784157440)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-570, started daemon 140046784157440)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-570, started daemon 140046784157440)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f5f3913ae10>>
    └ <Thread(Thread-570, started daemon 140046784157440)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 61632)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f5f38c47e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f5f3913ae10>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f5f3913ae10>
    │    │                   │        └ ('127.0.0.1', 61632)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f5f3913ae10>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f5f37cf3b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f5f2f5774e0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f5f37cf3bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f5f2f5774e0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f5f37cf30d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f5f3913ae10>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f5f2f5774e0>
    │       └ <function BaseHandler.run at 0x7f5f37cead90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f5f2f5778d0>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f5f37cf0158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f5f2f5778d0>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f5f2f5778d0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f5f366b7e10>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f5f2f5778d0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │    └ <function BaseHandler.get_response at 0x7f5f37e79840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f5f366b7e10>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-52/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fefa60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f5f366b7e10>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f5f34fb90f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fef730>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f5f34fb90f0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f5f34fb9fd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fefb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f5f34fb9fd0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f5f34fb9898>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fef840>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f5f34fb9898>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f5f35a27b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fefc80>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f5f35a27b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f5f35a27be0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34feff28>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f5f35a27be0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f5f35a27ac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fefea0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f5f35a27ac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f5f35a27b00>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fefd90>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f5f35a27b00>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f5f34f6acf8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fefd08>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f5f34f6acf8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f5f34f6a128>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               │    └ <function BaseHandler._get_response at 0x7f5f34fefe18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f5f34f6a128>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f5f366b7e10>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 52}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-52/'>
               └ <function doc at 0x7f5f358d9598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 52}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-52/'>
           └ <function doc at 0x7f5f358d9510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 52
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f5f37df8f60>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 52, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f5f38d0f8c8>
                   └ <django.db.models.manager.Manager object at 0x7f5f3505bf60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-28 16:07:19.895 | ERROR    | app_doc.util_upload_img:url_img_upload:301 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-18_1005570.4841046817647092.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-18_1005570.4841046817647092.png?",)
2021-08-28 18:29:05.086 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f5f3f08f378>
    └ <Thread(Thread-1653, started daemon 140046774191872)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f5f3f08f158>
    └ <Thread(Thread-1653, started daemon 140046774191872)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1653, started daemon 140046774191872)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1653, started daemon 140046774191872)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f5f3913ae10>>
    └ <Thread(Thread-1653, started daemon 140046774191872)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 64040)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f5f38c47e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f5f3913ae10>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f5f3913ae10>
    │    │                   │        └ ('127.0.0.1', 64040)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f5f3913ae10>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f5f37cf3b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f5f2e5186a0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f5f37cf3bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f5f2e5186a0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f5f37cf30d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f5f3913ae10>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f5f2e5186a0>
    │       └ <function BaseHandler.run at 0x7f5f37cead90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f5f1f263160>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f5f37cf0158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f5f1f263160>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f5f1f263160>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f5f366b7e10>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f5f1f263160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │    └ <function BaseHandler.get_response at 0x7f5f37e79840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f5f366b7e10>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-512/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fefa60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f5f366b7e10>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f5f34fb90f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fef730>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f5f34fb90f0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f5f34fb9fd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fefb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f5f34fb9fd0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f5f34fb9898>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fef840>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f5f34fb9898>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f5f35a27b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fefc80>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f5f35a27b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f5f35a27be0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34feff28>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f5f35a27be0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f5f35a27ac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fefea0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f5f35a27ac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f5f35a27b00>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fefd90>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f5f35a27b00>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f5f34f6acf8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f5f34fefd08>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f5f34f6acf8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f5f34f6a128>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               │    └ <function BaseHandler._get_response at 0x7f5f34fefe18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f5f34f6a128>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f5f366b7e10>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 512}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-512/'>
               └ <function doc at 0x7f5f358d9598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 512}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-512/'>
           └ <function doc at 0x7f5f358d9510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 512
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f5f37df8f60>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 512, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f5f38d0f8c8>
                   └ <django.db.models.manager.Manager object at 0x7f5f3505bf60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
