2022-07-21 20:30:29.360 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd5eb760ea0>
    └ <Thread(Thread-166, started daemon 140556471310080)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd5eb760c80>
    └ <Thread(Thread-166, started daemon 140556471310080)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-166, started daemon 140556471310080)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-166, started daemon 140556471310080)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>>
    └ <Thread(Thread-166, started daemon 140556471310080)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 58988)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fd5e46fa158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │    │                   │        └ ('127.0.0.1', 58988)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fd5e34f66a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5e07e05c0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fd5e34f6730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5e07e05c0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fd5e34f4bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5e07e05c0>
    │       └ <function BaseHandler.run at 0x7fd5e34f2950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e0828f28>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fd5e34f2c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e0828f28>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e0828f28>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e0828f28>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │    └ <function BaseHandler.get_response at 0x7fd5e3528e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-732/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751b70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07519d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07518c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │    └ <function BaseHandler._get_response at 0x7fd5e07b4e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 732}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <function doc at 0x7fd5e125a048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 732}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-732/'>
           └ <function doc at 0x7fd5e1256f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 732
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fd5e35f8ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 732, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fd5e47b3d08>
                   └ <django.db.models.manager.Manager object at 0x7fd5e2c9f128>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-21 23:59:24.338 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd5eb760ea0>
    └ <Thread(Thread-317, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd5eb760c80>
    └ <Thread(Thread-317, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-317, started daemon 140556481537792)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-317, started daemon 140556481537792)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>>
    └ <Thread(Thread-317, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60136)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fd5e46fa158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │    │                   │        └ ('127.0.0.1', 60136)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fd5e34f66a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d0517630>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fd5e34f6730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d0517630>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fd5e34f4bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d0517630>
    │       └ <function BaseHandler.run at 0x7fd5e34f2950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e077c198>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fd5e34f2c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e077c198>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e077c198>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e077c198>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │    └ <function BaseHandler.get_response at 0x7fd5e3528e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-338/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751b70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07519d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07518c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │    └ <function BaseHandler._get_response at 0x7fd5e07b4e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 338}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <function doc at 0x7fd5e125a048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 338}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-338/'>
           └ <function doc at 0x7fd5e1256f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 338
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fd5e35f8ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 338, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fd5e47b3d08>
                   └ <django.db.models.manager.Manager object at 0x7fd5e2c9f128>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-22 00:55:25.695 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd5eb760ea0>
    └ <Thread(Thread-327, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd5eb760c80>
    └ <Thread(Thread-327, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-327, started daemon 140556481537792)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-327, started daemon 140556481537792)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>>
    └ <Thread(Thread-327, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60314)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fd5e46fa158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │    │                   │        └ ('127.0.0.1', 60314)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fd5e34f66a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5e074a9b0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fd5e34f6730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5e074a9b0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fd5e34f4bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5e074a9b0>
    │       └ <function BaseHandler.run at 0x7fd5e34f2950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e34f94a8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fd5e34f2c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e34f94a8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e34f94a8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e34f94a8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               │    └ <function BaseHandler.get_response at 0x7fd5e3528e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-519/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751b70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07519d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07518c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               │    └ <function BaseHandler._get_response at 0x7fd5e07b4e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-519/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 519}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-519/'>
               └ <function doc at 0x7fd5e125a048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 519}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-519/'>
           └ <function doc at 0x7fd5e1256f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 519
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fd5e35f8ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 519, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fd5e47b3d08>
                   └ <django.db.models.manager.Manager object at 0x7fd5e2c9f128>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-22 02:25:25.483 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd5eb760ea0>
    └ <Thread(Thread-340, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd5eb760c80>
    └ <Thread(Thread-340, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-340, started daemon 140556481537792)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-340, started daemon 140556481537792)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>>
    └ <Thread(Thread-340, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60546)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fd5e46fa158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │    │                   │        └ ('127.0.0.1', 60546)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fd5e34f66a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5e0819748>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fd5e34f6730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5e0819748>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fd5e34f4bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5e0819748>
    │       └ <function BaseHandler.run at 0x7fd5e34f2950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5da039438>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fd5e34f2c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5da039438>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5da039438>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5da039438>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │    └ <function BaseHandler.get_response at 0x7fd5e3528e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-521/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751b70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07519d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07518c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │    └ <function BaseHandler._get_response at 0x7fd5e07b4e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 521}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <function doc at 0x7fd5e125a048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 521}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-521/'>
           └ <function doc at 0x7fd5e1256f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 521
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fd5e35f8ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 521, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fd5e47b3d08>
                   └ <django.db.models.manager.Manager object at 0x7fd5e2c9f128>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-22 02:56:49.113 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd5eb760ea0>
    └ <Thread(Thread-344, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd5eb760c80>
    └ <Thread(Thread-344, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-344, started daemon 140556481537792)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-344, started daemon 140556481537792)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>>
    └ <Thread(Thread-344, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60628)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fd5e46fa158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │    │                   │        └ ('127.0.0.1', 60628)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fd5e34f66a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5e0819748>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fd5e34f6730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5e0819748>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fd5e34f4bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5e0819748>
    │       └ <function BaseHandler.run at 0x7fd5e34f2950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9f8e5f8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fd5e34f2c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9f8e5f8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9f8e5f8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9f8e5f8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │    └ <function BaseHandler.get_response at 0x7fd5e3528e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-510/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751b70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07519d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07518c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │    └ <function BaseHandler._get_response at 0x7fd5e07b4e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 510}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <function doc at 0x7fd5e125a048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 510}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-510/'>
           └ <function doc at 0x7fd5e1256f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 510
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fd5e35f8ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 510, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fd5e47b3d08>
                   └ <django.db.models.manager.Manager object at 0x7fd5e2c9f128>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-22 03:25:24.551 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd5eb760ea0>
    └ <Thread(Thread-348, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd5eb760c80>
    └ <Thread(Thread-348, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-348, started daemon 140556481537792)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-348, started daemon 140556481537792)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>>
    └ <Thread(Thread-348, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60700)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fd5e46fa158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │    │                   │        └ ('127.0.0.1', 60700)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fd5e34f66a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5da039438>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fd5e34f6730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5da039438>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fd5e34f4bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5da039438>
    │       └ <function BaseHandler.run at 0x7fd5e34f2950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9fde3c8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fd5e34f2c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9fde3c8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9fde3c8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9fde3c8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │    └ <function BaseHandler.get_response at 0x7fd5e3528e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-523/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751b70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07519d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07518c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │    └ <function BaseHandler._get_response at 0x7fd5e07b4e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 523}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <function doc at 0x7fd5e125a048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 523}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-523/'>
           └ <function doc at 0x7fd5e1256f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 523
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fd5e35f8ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 523, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fd5e47b3d08>
                   └ <django.db.models.manager.Manager object at 0x7fd5e2c9f128>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-22 06:20:02.606 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd5eb760ea0>
    └ <Thread(Thread-381, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd5eb760c80>
    └ <Thread(Thread-381, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-381, started daemon 140556481537792)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-381, started daemon 140556481537792)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>>
    └ <Thread(Thread-381, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 32960)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fd5e46fa158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │    │                   │        └ ('127.0.0.1', 32960)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fd5e34f66a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d9f48f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fd5e34f6730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d9f48f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fd5e34f4bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d9f48f98>
    │       └ <function BaseHandler.run at 0x7fd5e34f2950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e07d5780>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fd5e34f2c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e07d5780>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e07d5780>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e07d5780>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               │    └ <function BaseHandler.get_response at 0x7fd5e3528e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-533/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751b70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07519d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07518c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               │    └ <function BaseHandler._get_response at 0x7fd5e07b4e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-533/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 533}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-533/'>
               └ <function doc at 0x7fd5e125a048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 533}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-533/'>
           └ <function doc at 0x7fd5e1256f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 533
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fd5e35f8ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 533, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fd5e47b3d08>
                   └ <django.db.models.manager.Manager object at 0x7fd5e2c9f128>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-22 06:46:00.133 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd5eb760ea0>
    └ <Thread(Thread-384, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd5eb760c80>
    └ <Thread(Thread-384, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-384, started daemon 140556481537792)>
    │    │        │    └ (<socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-384, started daemon 140556481537792)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>>
    └ <Thread(Thread-384, started daemon 140556481537792)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 33028)
    │    │              └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fd5e46fa158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │    │                   │        └ ('127.0.0.1', 33028)
    │    │                   └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fd5e34f66a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d9ba6898>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fd5e34f6730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d9ba6898>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fd5e34f4bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d9ba6898>
    │       └ <function BaseHandler.run at 0x7fd5e34f2950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9ba6a20>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fd5e34f2c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9ba6a20>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9ba6a20>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9ba6a20>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │    └ <function BaseHandler.get_response at 0x7fd5e3528e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-522/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751b70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07519d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07518c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │    └ <function BaseHandler._get_response at 0x7fd5e07b4e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 522}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <function doc at 0x7fd5e125a048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 522}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-522/'>
           └ <function doc at 0x7fd5e1256f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 522
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fd5e35f8ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 522, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fd5e47b3d08>
                   └ <django.db.models.manager.Manager object at 0x7fd5e2c9f128>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-22 12:51:58.249 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd5eb760ea0>
    └ <Thread(Thread-590, started daemon 140556471310080)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd5eb760c80>
    └ <Thread(Thread-590, started daemon 140556471310080)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-590, started daemon 140556471310080)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-590, started daemon 140556471310080)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>>
    └ <Thread(Thread-590, started daemon 140556471310080)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 35342)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fd5e46fa158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │    │                   │        └ ('127.0.0.1', 35342)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fd5e34f66a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d04eb940>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fd5e34f6730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d04eb940>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fd5e34f4bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d04eb940>
    │       └ <function BaseHandler.run at 0x7fd5e34f2950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9f8e5f8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fd5e34f2c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9f8e5f8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9f8e5f8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9f8e5f8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function BaseHandler.get_response at 0x7fd5e3528e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751b70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07519d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07518c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function BaseHandler._get_response at 0x7fd5e07b4e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 26, 'doc_id': 306}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <function doc at 0x7fd5e125a048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 26, 'doc_id': 306}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-26/doc-306/'>
           └ <function doc at 0x7fd5e1256f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 306
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fd5e35f8ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 306, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fd5e47b3d08>
                   └ <django.db.models.manager.Manager object at 0x7fd5e2c9f128>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-22 14:16:10.860 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd5eb760ea0>
    └ <Thread(Thread-597, started daemon 140556471310080)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd5eb760c80>
    └ <Thread(Thread-597, started daemon 140556471310080)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-597, started daemon 140556471310080)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-597, started daemon 140556471310080)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>>
    └ <Thread(Thread-597, started daemon 140556471310080)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 35564)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fd5e46fa158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │    │                   │        └ ('127.0.0.1', 35564)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fd5e34f66a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d81411d0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fd5e34f6730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d81411d0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fd5e34f4bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d81411d0>
    │       └ <function BaseHandler.run at 0x7fd5e34f2950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e001c828>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fd5e34f2c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e001c828>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e001c828>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5e001c828>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │    └ <function BaseHandler.get_response at 0x7fd5e3528e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-536/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751b70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07519d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07518c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               │    └ <function BaseHandler._get_response at 0x7fd5e07b4e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 536}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-536/'>
               └ <function doc at 0x7fd5e125a048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 536}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-536/'>
           └ <function doc at 0x7fd5e1256f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 536
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fd5e35f8ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 536, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fd5e47b3d08>
                   └ <django.db.models.manager.Manager object at 0x7fd5e2c9f128>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-22 19:23:59.866 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd5eb760ea0>
    └ <Thread(Thread-828, started daemon 140556160202496)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd5eb760c80>
    └ <Thread(Thread-828, started daemon 140556160202496)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-828, started daemon 140556160202496)>
    │    │        │    └ (<socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-828, started daemon 140556160202496)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>>
    └ <Thread(Thread-828, started daemon 140556160202496)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 38278)
    │    │              └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fd5e46fa158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │    │                   │        └ ('127.0.0.1', 38278)
    │    │                   └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fd5e34f66a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d9bd0550>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fd5e34f6730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d9bd0550>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fd5e34f4bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fd5e4e4afd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fd5d9bd0550>
    │       └ <function BaseHandler.run at 0x7fd5e34f2950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9bd0eb8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fd5e34f2c80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9bd0eb8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9bd0eb8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fd5d9bd0eb8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │    └ <function BaseHandler.get_response at 0x7fd5e3528e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-344/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751d08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fd5e07880f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751c80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fd5e0788668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751bf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fd5e07889e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751b70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fd5e0791710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751ae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fd5e0791198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751a60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fd5e13a8a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07519d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fd5e13a8b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e0751950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fd5e13a8ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fd5e07518c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fd5e13a8a58>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │    └ <function BaseHandler._get_response at 0x7fd5e07b4e18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fd5e2030a20>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fd5e1394f60>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 344}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <function doc at 0x7fd5e125a048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 344}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-344/'>
           └ <function doc at 0x7fd5e1256f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 344
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fd5e35f8ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 344, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fd5e47b3d08>
                   └ <django.db.models.manager.Manager object at 0x7fd5e2c9f128>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
