2022-05-14 01:27:26.362 | ERROR    | app_doc.views:doc:1073 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6038863ea0>
    └ <Thread(Thread-547, started daemon 140050939496192)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6038863c80>
    └ <Thread(Thread-547, started daemon 140050939496192)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-547, started daemon 140050939496192)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-547, started daemon 140050939496192)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f6031f52da0>>
    └ <Thread(Thread-547, started daemon 140050939496192)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60678)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f60318010d0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f6031f52da0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f6031f52da0>
    │    │                   │        └ ('127.0.0.1', 60678)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f6031f52da0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f60305e5ea0>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f602c38d828>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f60305e5f28>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f602c38d828>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f60305e5488>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f6031f52da0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f602c38d828>
    │       └ <function BaseHandler.run at 0x7f60305e21e0>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f602c4a8828>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f60305e2510>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f602c4a8828>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f602c4a8828>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f602e484c50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f602c4a8828>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function BaseHandler.get_response at 0x7f60306296a8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f602e484c50>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f602d8dd8c8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f602e484c50>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f602d90c470>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f602d8dd840>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f602d90c470>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f602d90c518>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f602d8dd7b8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f602d90c518>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f602e495cc0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f602d8dd730>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f602e495cc0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f602e495e10>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f602d8dd620>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f602e495e10>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f602e495d68>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f602d8dd598>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f602e495d68>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f602f05c8d0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f602d8dd6a8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f602f05c8d0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f602f05c6a0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f602d93fae8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f602f05c6a0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f602d918860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f602d93fa60>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f602d918860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f602d918208>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function BaseHandler._get_response at 0x7f602da23f28>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f602d918208>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f602e484c50>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 323}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <function doc at 0x7f602e3492f0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 323}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-323/'>
           └ <function doc at 0x7f602e349268>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1000, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 323
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f60306ec588>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 323, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f60318bac80>
                   └ <django.db.models.manager.Manager object at 0x7f60305f7d30>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
