2022-05-01 09:20:40.486 | ERROR    | app_doc.views:doc:1073 - Collection browsing error
Traceback (most recent call last):
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fdc63436510>
    └ <Thread(Thread-728, started daemon 140584161351424)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fdc634362f0>
    └ <Thread(Thread-728, started daemon 140584161351424)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-728, started daemon 140584161351424)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-728, started daemon 140584161351424)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>>
    └ <Thread(Thread-728, started daemon 140584161351424)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 45892)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fdc5e2a5bf8>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │    │                   │        └ ('127.0.0.1', 45892)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fdc5d2a4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc5463a4a8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fdc5d2a4c80>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc5463a4a8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fdc5d2a4268>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc5463a4a8>
    │       └ <function BaseHandler.run at 0x7fdc5d299f28>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc5509e518>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fdc5d2a02f0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc5509e518>
    │    │        │           │    └ {'LC_ALL': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc5509e518>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc5509e518>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │    └ <function BaseHandler.get_response at 0x7fdc5d2e6488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-732/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549c80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549bf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549b70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549ae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549a60>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565499d8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549950>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565498c8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549840>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 35, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │    └ <function BaseHandler._get_response at 0x7fdc56799048>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 732}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <function doc at 0x7fdc57052950>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 732}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-732/'>
           └ <function doc at 0x7fdc570528c8>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1000, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 732
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fdc5d3ab1d0>
          └ <class 'app_doc.models.Doc'>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 732, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fdc5e36fae8>
                   └ <django.db.models.manager.Manager object at 0x7fdc56671da0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-05-01 10:25:06.253 | ERROR    | app_doc.views:doc:1073 - Collection browsing error
Traceback (most recent call last):
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fdc63436510>
    └ <Thread(Thread-742, started daemon 140584295446272)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fdc634362f0>
    └ <Thread(Thread-742, started daemon 140584295446272)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-742, started daemon 140584295446272)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-742, started daemon 140584295446272)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>>
    └ <Thread(Thread-742, started daemon 140584295446272)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 45948)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fdc5e2a5bf8>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │    │                   │        └ ('127.0.0.1', 45948)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fdc5d2a4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc54668c88>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fdc5d2a4c80>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc54668c88>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fdc5d2a4268>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc54668c88>
    │       └ <function BaseHandler.run at 0x7fdc5d299f28>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc547c1da0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fdc5d2a02f0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc547c1da0>
    │    │        │           │    └ {'LC_ALL': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc547c1da0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc547c1da0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │    └ <function BaseHandler.get_response at 0x7fdc5d2e6488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-510/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549c80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549bf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549b70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549ae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549a60>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565499d8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549950>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565498c8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549840>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 35, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │    └ <function BaseHandler._get_response at 0x7fdc56799048>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 510}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <function doc at 0x7fdc57052950>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 510}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-510/'>
           └ <function doc at 0x7fdc570528c8>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1000, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 510
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fdc5d3ab1d0>
          └ <class 'app_doc.models.Doc'>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 510, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fdc5e36fae8>
                   └ <django.db.models.manager.Manager object at 0x7fdc56671da0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-05-01 12:46:54.482 | ERROR    | app_doc.views:doc:1073 - 文集浏览出错
Traceback (most recent call last):
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fdc63436510>
    └ <Thread(Thread-876, started daemon 140583809054464)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fdc634362f0>
    └ <Thread(Thread-876, started daemon 140583809054464)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-876, started daemon 140583809054464)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-876, started daemon 140583809054464)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>>
    └ <Thread(Thread-876, started daemon 140583809054464)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 46286)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fdc5e2a5bf8>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │    │                   │        └ ('127.0.0.1', 46286)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fdc5d2a4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc55074ac8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fdc5d2a4c80>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc55074ac8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fdc5d2a4268>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc55074ac8>
    │       └ <function BaseHandler.run at 0x7fdc5d299f28>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc54515668>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fdc5d2a02f0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc54515668>
    │    │        │           │    └ {'LC_ALL': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc54515668>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc54515668>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler.get_response at 0x7fdc5d2e6488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549c80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549bf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549b70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549ae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549a60>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565499d8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549950>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565498c8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549840>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 35, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler._get_response at 0x7fdc56799048>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 53}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <function doc at 0x7fdc57052950>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 53}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-53/'>
           └ <function doc at 0x7fdc570528c8>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1000, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 53
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fdc5d3ab1d0>
          └ <class 'app_doc.models.Doc'>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 53, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fdc5e36fae8>
                   └ <django.db.models.manager.Manager object at 0x7fdc56671da0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-05-01 16:03:34.993 | ERROR    | app_doc.views:doc:1073 - Collection browsing error
Traceback (most recent call last):
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fdc63436510>
    └ <Thread(Thread-1061, started daemon 140584186529536)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fdc634362f0>
    └ <Thread(Thread-1061, started daemon 140584186529536)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1061, started daemon 140584186529536)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1061, started daemon 140584186529536)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>>
    └ <Thread(Thread-1061, started daemon 140584186529536)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 46736)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fdc5e2a5bf8>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │    │                   │        └ ('127.0.0.1', 46736)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fdc5d2a4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc54515ac8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fdc5d2a4c80>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc54515ac8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fdc5d2a4268>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc54515ac8>
    │       └ <function BaseHandler.run at 0x7fdc5d299f28>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc5454d898>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fdc5d2a02f0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc5454d898>
    │    │        │           │    └ {'LC_ALL': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc5454d898>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc5454d898>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │    └ <function BaseHandler.get_response at 0x7fdc5d2e6488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-338/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549c80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549bf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549b70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549ae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549a60>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565499d8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549950>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565498c8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549840>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 35, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               │    └ <function BaseHandler._get_response at 0x7fdc56799048>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 338}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-338/'>
               └ <function doc at 0x7fdc57052950>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 338}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-338/'>
           └ <function doc at 0x7fdc570528c8>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1000, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 338
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fdc5d3ab1d0>
          └ <class 'app_doc.models.Doc'>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 338, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fdc5e36fae8>
                   └ <django.db.models.manager.Manager object at 0x7fdc56671da0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-05-01 20:41:52.637 | ERROR    | app_doc.views:doc:1073 - 文集浏览出错
Traceback (most recent call last):
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fdc63436510>
    └ <Thread(Thread-1182, started daemon 140584186529536)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fdc634362f0>
    └ <Thread(Thread-1182, started daemon 140584186529536)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1182, started daemon 140584186529536)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1182, started daemon 140584186529536)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>>
    └ <Thread(Thread-1182, started daemon 140584186529536)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 47350)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fdc5e2a5bf8>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │    │                   │        └ ('127.0.0.1', 47350)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fdc5d2a4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc5505b1d0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fdc5d2a4c80>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc5505b1d0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fdc5d2a4268>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc5505b1d0>
    │       └ <function BaseHandler.run at 0x7fdc5d299f28>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc565d4b38>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fdc5d2a02f0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc565d4b38>
    │    │        │           │    └ {'LC_ALL': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc565d4b38>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc565d4b38>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function BaseHandler.get_response at 0x7fdc5d2e6488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549c80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549bf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549b70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549ae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549a60>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565499d8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549950>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565498c8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549840>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 35, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function BaseHandler._get_response at 0x7fdc56799048>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 323}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <function doc at 0x7fdc57052950>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 323}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-323/'>
           └ <function doc at 0x7fdc570528c8>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1000, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 323
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fdc5d3ab1d0>
          └ <class 'app_doc.models.Doc'>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 323, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fdc5e36fae8>
                   └ <django.db.models.manager.Manager object at 0x7fdc56671da0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
