2021-08-03 20:19:42.986 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbcb4ecb378>
    └ <Thread(Thread-179, started daemon 140448193382144)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbcb4ecb158>
    └ <Thread(Thread-179, started daemon 140448193382144)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-179, started daemon 140448193382144)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-179, started daemon 140448193382144)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>>
    └ <Thread(Thread-179, started daemon 140448193382144)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 9538)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbcaea83e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │    │                   │        └ ('127.0.0.1', 9538)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbcadb2fb70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca426edd8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbcadb2fbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca426edd8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbcadb2f0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca426edd8>
    │       └ <function BaseHandler.run at 0x7fbcadb27d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca5342a20>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbcadb2c158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca5342a20>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca5342a20>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca5342a20>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function BaseHandler.get_response at 0x7fbcadcb6840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db67b8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6048>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db60d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db61e0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db62f0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6378>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6510>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function BaseHandler._get_response at 0x7fbca6db6598>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 161}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <function doc at 0x7fbcac06f598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 161}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-161/'>
           └ <function doc at 0x7fbcac06f510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 161
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbcadc40048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 161, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbcaeb4b8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbca6e917f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-03 21:29:15.325 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbcb4ecb378>
    └ <Thread(Thread-231, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbcb4ecb158>
    └ <Thread(Thread-231, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-231, started daemon 140448212788992)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-231, started daemon 140448212788992)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>>
    └ <Thread(Thread-231, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 9738)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbcaea83e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │    │                   │        └ ('127.0.0.1', 9738)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbcadb2fb70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca5e24f60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbcadb2fbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca5e24f60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbcadb2f0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca5e24f60>
    │       └ <function BaseHandler.run at 0x7fbcadb27d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca42924a8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbcadb2c158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca42924a8>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca42924a8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca42924a8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               │    └ <function BaseHandler.get_response at 0x7fbcadcb6840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-50/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db67b8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6048>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db60d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db61e0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db62f0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6378>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6510>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               │    └ <function BaseHandler._get_response at 0x7fbca6db6598>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-50/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 50}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-50/'>
               └ <function doc at 0x7fbcac06f598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 50}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-50/'>
           └ <function doc at 0x7fbcac06f510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 50
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbcadc40048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 50, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbcaeb4b8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbca6e917f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-04 03:40:19.689 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbcb4ecb378>
    └ <Thread(Thread-403, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbcb4ecb158>
    └ <Thread(Thread-403, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-403, started daemon 140448212788992)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-403, started daemon 140448212788992)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>>
    └ <Thread(Thread-403, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 10472)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbcaea83e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │    │                   │        └ ('127.0.0.1', 10472)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbcadb2fb70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca42924a8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbcadb2fbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca42924a8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbcadb2f0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca42924a8>
    │       └ <function BaseHandler.run at 0x7fbcadb27d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbcafd0c588>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbcadb2c158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbcafd0c588>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbcafd0c588>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbcafd0c588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │    └ <function BaseHandler.get_response at 0x7fbcadcb6840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-82/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db67b8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6048>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db60d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db61e0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db62f0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6378>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6510>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │    └ <function BaseHandler._get_response at 0x7fbca6db6598>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 82}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <function doc at 0x7fbcac06f598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 82}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-82/'>
           └ <function doc at 0x7fbcac06f510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 82
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbcadc40048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 82, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbcaeb4b8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbca6e917f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-04 03:50:20.045 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbcb4ecb378>
    └ <Thread(Thread-406, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbcb4ecb158>
    └ <Thread(Thread-406, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-406, started daemon 140448212788992)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-406, started daemon 140448212788992)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>>
    └ <Thread(Thread-406, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 10498)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbcaea83e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │    │                   │        └ ('127.0.0.1', 10498)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbcadb2fb70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca40d1748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbcadb2fbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca40d1748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbcadb2f0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca40d1748>
    │       └ <function BaseHandler.run at 0x7fbcadb27d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca40f5198>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbcadb2c158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca40f5198>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca40f5198>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca40f5198>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │    └ <function BaseHandler.get_response at 0x7fbcadcb6840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-82/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db67b8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6048>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db60d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db61e0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db62f0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6378>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6510>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │    └ <function BaseHandler._get_response at 0x7fbca6db6598>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 82}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <function doc at 0x7fbcac06f598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 82}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-82/'>
           └ <function doc at 0x7fbcac06f510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 82
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbcadc40048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 82, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbcaeb4b8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbca6e917f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-04 04:20:17.555 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbcb4ecb378>
    └ <Thread(Thread-413, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbcb4ecb158>
    └ <Thread(Thread-413, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-413, started daemon 140448212788992)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-413, started daemon 140448212788992)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>>
    └ <Thread(Thread-413, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 10552)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbcaea83e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │    │                   │        └ ('127.0.0.1', 10552)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbcadb2fb70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca40e3550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbcadb2fbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca40e3550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbcadb2f0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca40e3550>
    │       └ <function BaseHandler.run at 0x7fbcadb27d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca5df2278>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbcadb2c158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca5df2278>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca5df2278>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca5df2278>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │    └ <function BaseHandler.get_response at 0x7fbcadcb6840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-85/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db67b8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6048>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db60d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db61e0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db62f0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6378>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6510>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │    └ <function BaseHandler._get_response at 0x7fbca6db6598>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 85}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <function doc at 0x7fbcac06f598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 85}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-85/'>
           └ <function doc at 0x7fbcac06f510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 85
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbcadc40048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 85, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbcaeb4b8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbca6e917f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-04 11:34:27.346 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_153107.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_153107.png?",)
2021-08-04 11:34:27.328 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1737060.37733254829039.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1737060.37733254829039.png?",)
2021-08-04 11:34:27.366 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_0947410.23325597268259834.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_0947410.23325597268259834.png?",)
2021-08-04 11:34:27.391 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1035250.31094488351753713.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1035250.31094488351753713.png?",)
2021-08-04 11:34:27.409 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1615400.49959836104551203.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1615400.49959836104551203.png?",)
2021-08-04 13:29:14.770 | ERROR    | app_doc.views:doc:1022 - Collection browsing error
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbcb4ecb378>
    └ <Thread(Thread-534, started daemon 140448201774848)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbcb4ecb158>
    └ <Thread(Thread-534, started daemon 140448201774848)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-534, started daemon 140448201774848)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-534, started daemon 140448201774848)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>>
    └ <Thread(Thread-534, started daemon 140448201774848)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 11548)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbcaea83e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │    │                   │        └ ('127.0.0.1', 11548)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbcadb2fb70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca422d5c0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbcadb2fbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca422d5c0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbcadb2f0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca422d5c0>
    │       └ <function BaseHandler.run at 0x7fbcadb27d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca41b7400>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbcadb2c158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca41b7400>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca41b7400>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca41b7400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │    └ <function BaseHandler.get_response at 0x7fbcadcb6840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-510/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db67b8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6048>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db60d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db61e0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db62f0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6378>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6510>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               │    └ <function BaseHandler._get_response at 0x7fbca6db6598>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 510}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-510/'>
               └ <function doc at 0x7fbcac06f598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 510}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-510/'>
           └ <function doc at 0x7fbcac06f510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 510
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbcadc40048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 510, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbcaeb4b8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbca6e917f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-04 16:27:33.830 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_153107.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_153107.png?",)
2021-08-04 16:27:33.846 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1140410.08117444125024054.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1140410.08117444125024054.png?",)
2021-08-04 16:27:33.856 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1035250.31094488351753713.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1035250.31094488351753713.png?",)
2021-08-04 16:27:33.867 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_0947410.23325597268259834.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_0947410.23325597268259834.png?",)
2021-08-04 16:27:33.879 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1514310.9596805483939324.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1514310.9596805483939324.png?",)
2021-08-04 16:27:33.891 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1537570.5383356998637554.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1537570.5383356998637554.png?",)
2021-08-04 16:27:33.904 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1624560.0730340580168457.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1624560.0730340580168457.png?",)
2021-08-04 16:27:33.915 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1600030.20263527686884708.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1600030.20263527686884708.png?",)
2021-08-04 16:27:33.926 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1550510.26064429955688506.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1550510.26064429955688506.png?",)
2021-08-04 16:27:33.936 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1737060.37733254829039.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1737060.37733254829039.png?",)
2021-08-04 16:27:33.947 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1615400.49959836104551203.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1615400.49959836104551203.png?",)
2021-08-04 16:27:35.295 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_153107.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_153107.png?",)
2021-08-04 16:27:35.312 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1615400.49959836104551203.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1615400.49959836104551203.png?",)
2021-08-04 16:27:35.329 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1737060.37733254829039.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1737060.37733254829039.png?",)
2021-08-04 16:27:35.362 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1035250.31094488351753713.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1035250.31094488351753713.png?",)
2021-08-04 16:27:35.367 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_0947410.23325597268259834.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_0947410.23325597268259834.png?",)
2021-08-04 16:27:35.379 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1140410.08117444125024054.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1140410.08117444125024054.png?",)
2021-08-04 16:27:35.391 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1514310.9596805483939324.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1514310.9596805483939324.png?",)
2021-08-04 16:27:35.410 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1537570.5383356998637554.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1537570.5383356998637554.png?",)
2021-08-04 16:27:35.422 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1550510.26064429955688506.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1550510.26064429955688506.png?",)
2021-08-04 16:27:35.436 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1600030.20263527686884708.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1600030.20263527686884708.png?",)
2021-08-04 16:27:35.452 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1624560.0730340580168457.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1624560.0730340580168457.png?",)
2021-08-04 17:09:10.319 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1615400.49959836104551203.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1615400.49959836104551203.png?",)
2021-08-04 17:09:10.328 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_153107.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_153107.png?",)
2021-08-04 17:09:27.304 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_153107.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_153107.png?",)
2021-08-04 17:09:27.321 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1615400.49959836104551203.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1615400.49959836104551203.png?",)
2021-08-04 17:09:31.644 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_153107.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_153107.png?",)
2021-08-04 17:09:31.658 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1615400.49959836104551203.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1615400.49959836104551203.png?",)
2021-08-04 17:09:31.669 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1737060.37733254829039.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1737060.37733254829039.png?",)
2021-08-04 17:09:31.689 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_0947410.23325597268259834.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_0947410.23325597268259834.png?",)
2021-08-04 17:09:31.700 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1035250.31094488351753713.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1035250.31094488351753713.png?",)
2021-08-04 17:09:31.714 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1140410.08117444125024054.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1140410.08117444125024054.png?",)
2021-08-04 17:09:31.725 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1514310.9596805483939324.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1514310.9596805483939324.png?",)
2021-08-04 17:09:31.737 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1537570.5383356998637554.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1537570.5383356998637554.png?",)
2021-08-04 17:09:31.748 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1550510.26064429955688506.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1550510.26064429955688506.png?",)
2021-08-04 17:09:31.758 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1600030.20263527686884708.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1600030.20263527686884708.png?",)
2021-08-04 17:09:31.769 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1624560.0730340580168457.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1624560.0730340580168457.png?",)
2021-08-04 17:13:34.986 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbcb4ecb378>
    └ <Thread(Thread-702, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbcb4ecb158>
    └ <Thread(Thread-702, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-702, started daemon 140448212788992)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-702, started daemon 140448212788992)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>>
    └ <Thread(Thread-702, started daemon 140448212788992)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 12160)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbcaea83e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │    │                   │        └ ('127.0.0.1', 12160)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbcadb2fb70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca40e3550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbcadb2fbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca40e3550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbcadb2f0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca40e3550>
    │       └ <function BaseHandler.run at 0x7fbcadb27d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbc962ce0b8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbcadb2c158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbc962ce0b8>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbc962ce0b8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbc962ce0b8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler.get_response at 0x7fbcadcb6840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db67b8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6048>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db60d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db61e0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db62f0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6378>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6510>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler._get_response at 0x7fbca6db6598>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 53}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <function doc at 0x7fbcac06f598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 53}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-53/'>
           └ <function doc at 0x7fbcac06f510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 53
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbcadc40048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 53, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbcaeb4b8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbca6e917f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-04 17:31:43.857 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1615400.49959836104551203.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1615400.49959836104551203.png?",)
2021-08-04 17:31:43.859 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_153107.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_153107.png?",)
2021-08-04 17:31:43.873 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1737060.37733254829039.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1737060.37733254829039.png?",)
2021-08-04 17:31:43.889 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_0947410.23325597268259834.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_0947410.23325597268259834.png?",)
2021-08-04 17:31:43.899 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1035250.31094488351753713.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1035250.31094488351753713.png?",)
2021-08-04 17:31:43.912 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1140410.08117444125024054.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1140410.08117444125024054.png?",)
2021-08-04 17:31:43.924 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1514310.9596805483939324.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1514310.9596805483939324.png?",)
2021-08-04 17:31:43.934 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1537570.5383356998637554.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1537570.5383356998637554.png?",)
2021-08-04 17:31:43.947 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1550510.26064429955688506.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1550510.26064429955688506.png?",)
2021-08-04 17:31:43.957 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1600030.20263527686884708.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1600030.20263527686884708.png?",)
2021-08-04 17:31:43.970 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1624560.0730340580168457.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1624560.0730340580168457.png?",)
2021-08-04 17:41:55.218 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_153107.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_153107.png?",)
2021-08-04 17:41:55.231 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1615400.49959836104551203.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1615400.49959836104551203.png?",)
2021-08-04 17:41:55.242 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1737060.37733254829039.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1737060.37733254829039.png?",)
2021-08-04 17:41:55.253 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_0947410.23325597268259834.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_0947410.23325597268259834.png?",)
2021-08-04 17:41:55.267 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1035250.31094488351753713.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1035250.31094488351753713.png?",)
2021-08-04 17:41:55.282 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1550510.26064429955688506.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1550510.26064429955688506.png?",)
2021-08-04 17:41:55.294 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1537570.5383356998637554.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1537570.5383356998637554.png?",)
2021-08-04 17:41:55.305 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1624560.0730340580168457.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1624560.0730340580168457.png?",)
2021-08-04 17:41:55.315 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1600030.20263527686884708.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1600030.20263527686884708.png?",)
2021-08-04 17:41:55.325 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1140410.08117444125024054.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1140410.08117444125024054.png?",)
2021-08-04 17:41:55.336 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1514310.9596805483939324.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1514310.9596805483939324.png?",)
2021-08-04 17:43:45.032 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_153107.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_153107.png?",)
2021-08-04 17:43:45.047 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1615400.49959836104551203.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1615400.49959836104551203.png?",)
2021-08-04 17:43:45.058 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-03_1737060.37733254829039.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-03_1737060.37733254829039.png?",)
2021-08-04 17:43:45.068 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_0947410.23325597268259834.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_0947410.23325597268259834.png?",)
2021-08-04 17:43:45.080 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1035250.31094488351753713.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1035250.31094488351753713.png?",)
2021-08-04 17:43:45.090 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1140410.08117444125024054.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1140410.08117444125024054.png?",)
2021-08-04 17:43:45.102 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1537570.5383356998637554.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1537570.5383356998637554.png?",)
2021-08-04 17:43:45.112 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1600030.20263527686884708.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1600030.20263527686884708.png?",)
2021-08-04 17:43:45.125 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1624560.0730340580168457.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1624560.0730340580168457.png?",)
2021-08-04 17:43:45.137 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1514310.9596805483939324.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1514310.9596805483939324.png?",)
2021-08-04 17:43:45.147 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-04_1550510.26064429955688506.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-04_1550510.26064429955688506.png?",)
