2021-08-05 23:33:07.074 | ERROR    | app_doc.views:project_index:408 - 文集页访问异常
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbcb4ecb378>
    └ <Thread(Thread-1894, started daemon 140447896217344)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbcb4ecb158>
    └ <Thread(Thread-1894, started daemon 140447896217344)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1894, started daemon 140447896217344)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1894, started daemon 140447896217344)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>>
    └ <Thread(Thread-1894, started daemon 140447896217344)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 16628)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbcaea83e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │    │                   │        └ ('127.0.0.1', 16628)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbcadb2fb70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca4100eb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbcadb2fbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca4100eb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbcadb2f0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca4100eb8>
    │       └ <function BaseHandler.run at 0x7fbcadb27d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbc962cf630>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbcadb2c158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbc962cf630>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbc962cf630>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbc962cf630>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-43/'>
               │    └ <function BaseHandler.get_response at 0x7fbcadcb6840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-43/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db67b8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6048>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db60d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db61e0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db62f0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6378>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6510>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-43/'>
               │    └ <function BaseHandler._get_response at 0x7fbca6db6598>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 43}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-43/'>
               └ <function check_headers.<locals>._inner at 0x7fbcac068488>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 43}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-43/'>
           └ <function check_headers.<locals>._inner at 0x7fbcac068400>

  File "/usr/local/projects/MrDoc/app_admin/decorators.py", line 43, in _inner
    return function(request, *args, **kwargs)
           │        │         │       └ {'pro_id': 43}
           │        │         └ ()
           │        └ <WSGIRequest: GET '/project-43/'>
           └ <function project_index at 0x7fbcac068378>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 339, in project_index
    project = Project.objects.get(id=int(pro_id))
              │       │                  └ 43
              │       └ <django.db.models.manager.ManagerDescriptor object at 0x7fbcadc2aa58>
              └ <class 'app_doc.models.Project'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 43}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbcaeb4b8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbca6e91400>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Project'
    │    │     └ <Options for Project>
    │    └ <class 'app_doc.models.Project'>
    └ <QuerySet [<Project: About>, <Project: Algorithm Notebook>, <Project: Common Commands>, <Project: Machine Learning>, <Project...

app_doc.models.Project.DoesNotExist: Project matching query does not exist.
2021-08-06 08:06:19.542 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbcb4ecb378>
    └ <Thread(Thread-1955, started daemon 140447887824640)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbcb4ecb158>
    └ <Thread(Thread-1955, started daemon 140447887824640)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1955, started daemon 140447887824640)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1955, started daemon 140447887824640)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>>
    └ <Thread(Thread-1955, started daemon 140447887824640)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 17370)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbcaea83e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │    │                   │        └ ('127.0.0.1', 17370)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbcadb2fb70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca4249f60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbcadb2fbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca4249f60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbcadb2f0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca4249f60>
    │       └ <function BaseHandler.run at 0x7fbcadb27d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbc92f859b0>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbcadb2c158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbc92f859b0>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbc92f859b0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbc92f859b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │    └ <function BaseHandler.get_response at 0x7fbcadcb6840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-82/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db67b8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6048>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db60d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db61e0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db62f0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6378>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6510>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               │    └ <function BaseHandler._get_response at 0x7fbca6db6598>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 82}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-82/'>
               └ <function doc at 0x7fbcac06f598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 82}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-82/'>
           └ <function doc at 0x7fbcac06f510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 82
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbcadc40048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 82, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbcaeb4b8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbca6e917f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-06 09:26:31.931 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbcb4ecb378>
    └ <Thread(Thread-1982, started daemon 140447887824640)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbcb4ecb158>
    └ <Thread(Thread-1982, started daemon 140447887824640)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1982, started daemon 140447887824640)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1982, started daemon 140447887824640)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>>
    └ <Thread(Thread-1982, started daemon 140447887824640)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 17510)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbcaea83e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │    │                   │        └ ('127.0.0.1', 17510)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbcadb2fb70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca4100eb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbcadb2fbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca4100eb8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbcadb2f0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbca4100eb8>
    │       └ <function BaseHandler.run at 0x7fbcadb27d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca5df2278>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbcadb2c158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca5df2278>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca5df2278>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca5df2278>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function BaseHandler.get_response at 0x7fbcadcb6840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db67b8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6048>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db60d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db61e0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db62f0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6378>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6510>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function BaseHandler._get_response at 0x7fbca6db6598>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 161}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <function doc at 0x7fbcac06f598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 161}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-161/'>
           └ <function doc at 0x7fbcac06f510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 161
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbcadc40048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 161, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbcaeb4b8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbca6e917f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-06 15:01:53.149 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：ConnectionError(MaxRetryError("HTTPSConnectionPool(host='filescdn.proginn.com', port=443): Max retries exceeded with url: /4aa029e6b3641616eab4875061add6de/aafab940ef4a051d04497233d6477df8.webp (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbca4096f98>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
2021-08-06 17:33:29.458 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbcb4ecb378>
    └ <Thread(Thread-2426, started daemon 140447879431936)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbcb4ecb158>
    └ <Thread(Thread-2426, started daemon 140447879431936)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2426, started daemon 140447879431936)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2426, started daemon 140447879431936)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>>
    └ <Thread(Thread-2426, started daemon 140447879431936)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 18972)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbcaea83e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │    │                   │        └ ('127.0.0.1', 18972)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbcadb2fb70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbc92f9eb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbcadb2fbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbc92f9eb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbcadb2f0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbcaef76eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbc92f9eb70>
    │       └ <function BaseHandler.run at 0x7fbcadb27d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca41aeb38>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbcadb2c158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca41aeb38>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca41aeb38>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbca41aeb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │    └ <function BaseHandler.get_response at 0x7fbcadcb6840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-85/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db67b8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6048>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbca6e21128>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db60d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbca6e21160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbcac1beac8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db61e0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbcac1beba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6268>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbcac1bec50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db62f0>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbcac1beb38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6378>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbcac1beb70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbca6db6510>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbca6e30588>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               │    └ <function BaseHandler._get_response at 0x7fbca6db6598>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbca6e30ba8>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbcac4f8e80>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 85}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-85/'>
               └ <function doc at 0x7fbcac06f598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 85}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-85/'>
           └ <function doc at 0x7fbcac06f510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 85
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbcadc40048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 85, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbcaeb4b8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbca6e917f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
