2022-07-27 01:24:39.557 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fa9b77f3ea0>
    └ <Thread(Thread-166, started daemon 140366592534272)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fa9b77f3c80>
    └ <Thread(Thread-166, started daemon 140366592534272)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-166, started daemon 140366592534272)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-166, started daemon 140366592534272)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>>
    └ <Thread(Thread-166, started daemon 140366592534272)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 34046)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fa9b078d158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
    │    │                   │        └ ('127.0.0.1', 34046)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fa9af58b7b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9afcd1e10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fa9af58b840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9afcd1e10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fa9af588d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9afcd1e10>
    │       └ <function BaseHandler.run at 0x7fa9af584a60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a5651630>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fa9af584d90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a5651630>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a5651630>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a5651630>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │    └ <function BaseHandler.get_response at 0x7fa9af5bcf28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-521/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a378>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7fa9ac7a8358>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a2f0>
               │           └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7fa9ac7a8358>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fa9ac7a85c0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a268>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fa9ac7a85c0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa9ac7a87f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a1e0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa9ac7a87f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fa9ac7a8b38>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fa9ac7a8b38>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fa9ac7a8dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a0d0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fa9ac7a8dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fa9ac7a8f98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a048>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fa9ac7a8f98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fa9ad27d3c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664ea0>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fa9ad27d3c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa9ad27d2e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664e18>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa9ad27d2e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa9ad27d128>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664f28>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa9ad27d128>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fa9ac699ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac6c5488>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fa9ac699ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fa9ad27d160>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac6c5510>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fa9ad27d160>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7fa9ac6a2b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function BaseHandler._get_response at 0x7fa9ac6c52f0>
               │           └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7fa9ac6a2b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 521}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <function doc at 0x7fa9ad1288c8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 521}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-521/'>
           └ <function doc at 0x7fa9ad128840>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 521
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fa9af692080>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 521, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fa9b0846d08>
                   └ <django.db.models.manager.Manager object at 0x7fa9aed1c860>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-27 02:50:17.760 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fa9b77f3ea0>
    └ <Thread(Thread-191, started daemon 140366592534272)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fa9b77f3c80>
    └ <Thread(Thread-191, started daemon 140366592534272)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-191, started daemon 140366592534272)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-191, started daemon 140366592534272)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>>
    └ <Thread(Thread-191, started daemon 140366592534272)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 34326)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fa9b078d158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
    │    │                   │        └ ('127.0.0.1', 34326)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fa9af58b7b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9a691d940>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fa9af58b840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9a691d940>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fa9af588d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9a691d940>
    │       └ <function BaseHandler.run at 0x7fa9af584a60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a672b8d0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fa9af584d90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a672b8d0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a672b8d0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a672b8d0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler.get_response at 0x7fa9af5bcf28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a378>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7fa9ac7a8358>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a2f0>
               │           └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7fa9ac7a8358>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fa9ac7a85c0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a268>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fa9ac7a85c0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa9ac7a87f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a1e0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa9ac7a87f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fa9ac7a8b38>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fa9ac7a8b38>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fa9ac7a8dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a0d0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fa9ac7a8dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fa9ac7a8f98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a048>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fa9ac7a8f98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fa9ad27d3c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664ea0>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fa9ad27d3c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa9ad27d2e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664e18>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa9ad27d2e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa9ad27d128>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664f28>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa9ad27d128>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fa9ac699ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac6c5488>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fa9ac699ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fa9ad27d160>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac6c5510>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fa9ad27d160>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7fa9ac6a2b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function BaseHandler._get_response at 0x7fa9ac6c52f0>
               │           └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7fa9ac6a2b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 273}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <function doc at 0x7fa9ad1288c8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 273}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-273/'>
           └ <function doc at 0x7fa9ad128840>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 273
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fa9af692080>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 273, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fa9b0846d08>
                   └ <django.db.models.manager.Manager object at 0x7fa9aed1c860>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-27 07:58:06.241 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fa9b77f3ea0>
    └ <Thread(Thread-284, started daemon 140366600926976)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fa9b77f3c80>
    └ <Thread(Thread-284, started daemon 140366600926976)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-284, started daemon 140366600926976)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-284, started daemon 140366600926976)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>>
    └ <Thread(Thread-284, started daemon 140366600926976)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 35254)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fa9b078d158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
    │    │                   │        └ ('127.0.0.1', 35254)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fa9af58b7b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9a681b9b0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fa9af58b840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9a681b9b0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fa9af588d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9a681b9b0>
    │       └ <function BaseHandler.run at 0x7fa9af584a60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a6833128>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fa9af584d90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a6833128>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a6833128>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a6833128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │    └ <function BaseHandler.get_response at 0x7fa9af5bcf28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-521/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a378>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7fa9ac7a8358>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a2f0>
               │           └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7fa9ac7a8358>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fa9ac7a85c0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a268>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fa9ac7a85c0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa9ac7a87f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a1e0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa9ac7a87f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fa9ac7a8b38>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fa9ac7a8b38>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fa9ac7a8dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a0d0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fa9ac7a8dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fa9ac7a8f98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a048>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fa9ac7a8f98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fa9ad27d3c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664ea0>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fa9ad27d3c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa9ad27d2e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664e18>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa9ad27d2e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa9ad27d128>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664f28>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa9ad27d128>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fa9ac699ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac6c5488>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fa9ac699ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fa9ad27d160>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac6c5510>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fa9ad27d160>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7fa9ac6a2b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               │           │    └ <function BaseHandler._get_response at 0x7fa9ac6c52f0>
               │           └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7fa9ac6a2b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 521}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-521/'>
               └ <function doc at 0x7fa9ad1288c8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 521}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-521/'>
           └ <function doc at 0x7fa9ad128840>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 521
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fa9af692080>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 521, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fa9b0846d08>
                   └ <django.db.models.manager.Manager object at 0x7fa9aed1c860>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-27 08:04:17.210 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fa9b77f3ea0>
    └ <Thread(Thread-286, started daemon 140366600926976)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fa9b77f3c80>
    └ <Thread(Thread-286, started daemon 140366600926976)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-286, started daemon 140366600926976)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-286, started daemon 140366600926976)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>>
    └ <Thread(Thread-286, started daemon 140366600926976)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 35278)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fa9b078d158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
    │    │                   │        └ ('127.0.0.1', 35278)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fa9af58b7b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9afcd1e10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fa9af58b840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9afcd1e10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fa9af588d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9afcd1e10>
    │       └ <function BaseHandler.run at 0x7fa9af584a60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a5651940>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fa9af584d90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a5651940>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a5651940>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a5651940>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler.get_response at 0x7fa9af5bcf28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a378>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7fa9ac7a8358>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a2f0>
               │           └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7fa9ac7a8358>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fa9ac7a85c0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a268>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fa9ac7a85c0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa9ac7a87f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a1e0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa9ac7a87f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fa9ac7a8b38>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fa9ac7a8b38>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fa9ac7a8dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a0d0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fa9ac7a8dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fa9ac7a8f98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a048>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fa9ac7a8f98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fa9ad27d3c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664ea0>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fa9ad27d3c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa9ad27d2e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664e18>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa9ad27d2e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa9ad27d128>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664f28>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa9ad27d128>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fa9ac699ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac6c5488>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fa9ac699ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fa9ad27d160>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac6c5510>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fa9ad27d160>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7fa9ac6a2b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function BaseHandler._get_response at 0x7fa9ac6c52f0>
               │           └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7fa9ac6a2b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 273}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <function doc at 0x7fa9ad1288c8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 273}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-273/'>
           └ <function doc at 0x7fa9ad128840>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 273
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fa9af692080>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 273, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fa9b0846d08>
                   └ <django.db.models.manager.Manager object at 0x7fa9aed1c860>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-27 12:04:22.693 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fa9b77f3ea0>
    └ <Thread(Thread-513, started daemon 140366609581824)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fa9b77f3c80>
    └ <Thread(Thread-513, started daemon 140366609581824)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-513, started daemon 140366609581824)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-513, started daemon 140366609581824)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>>
    └ <Thread(Thread-513, started daemon 140366609581824)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 37274)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fa9b078d158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
    │    │                   │        └ ('127.0.0.1', 37274)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fa9af58b7b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9b1a1d5c0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fa9af58b840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9b1a1d5c0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fa9af588d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9b1a1d5c0>
    │       └ <function BaseHandler.run at 0x7fa9af584a60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a654f588>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fa9af584d90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a654f588>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a654f588>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a654f588>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function BaseHandler.get_response at 0x7fa9af5bcf28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a378>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7fa9ac7a8358>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a2f0>
               │           └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7fa9ac7a8358>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fa9ac7a85c0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a268>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fa9ac7a85c0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa9ac7a87f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a1e0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa9ac7a87f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fa9ac7a8b38>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fa9ac7a8b38>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fa9ac7a8dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a0d0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fa9ac7a8dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fa9ac7a8f98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a048>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fa9ac7a8f98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fa9ad27d3c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664ea0>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fa9ad27d3c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa9ad27d2e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664e18>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa9ad27d2e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa9ad27d128>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664f28>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa9ad27d128>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fa9ac699ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac6c5488>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fa9ac699ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fa9ad27d160>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac6c5510>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fa9ad27d160>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7fa9ac6a2b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function BaseHandler._get_response at 0x7fa9ac6c52f0>
               │           └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7fa9ac6a2b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 26, 'doc_id': 306}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <function doc at 0x7fa9ad1288c8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 26, 'doc_id': 306}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-26/doc-306/'>
           └ <function doc at 0x7fa9ad128840>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 306
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fa9af692080>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 306, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fa9b0846d08>
                   └ <django.db.models.manager.Manager object at 0x7fa9aed1c860>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-27 17:15:53.988 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fa9b77f3ea0>
    └ <Thread(Thread-1039, started daemon 140366600926976)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fa9b77f3c80>
    └ <Thread(Thread-1039, started daemon 140366600926976)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1039, started daemon 140366600926976)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1039, started daemon 140366600926976)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>>
    └ <Thread(Thread-1039, started daemon 140366600926976)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 40030)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fa9b078d158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
    │    │                   │        └ ('127.0.0.1', 40030)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fa9af58b7b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9a668d2b0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fa9af58b840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9a668d2b0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fa9af588d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fa9b0c5d080>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fa9a668d2b0>
    │       └ <function BaseHandler.run at 0x7fa9af584a60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a717d630>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fa9af584d90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a717d630>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a717d630>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fa9a717d630>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │    └ <function BaseHandler.get_response at 0x7fa9af5bcf28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-522/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a378>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7fa9ac7a8358>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a2f0>
               │           └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7fa9ac7a8358>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fa9ac7a85c0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a268>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fa9ac7a85c0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa9ac7a87f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a1e0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fa9ac7a87f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fa9ac7a8b38>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a158>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fa9ac7a8b38>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fa9ac7a8dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a0d0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fa9ac7a8dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fa9ac7a8f98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac67a048>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fa9ac7a8f98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fa9ad27d3c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664ea0>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fa9ad27d3c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa9ad27d2e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664e18>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fa9ad27d2e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa9ad27d128>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac664f28>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fa9ad27d128>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fa9ac699ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac6c5488>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fa9ac699ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fa9ad27d160>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fa9ac6c5510>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fa9ad27d160>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7fa9ac6a2b70>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               │           │    └ <function BaseHandler._get_response at 0x7fa9ac6c52f0>
               │           └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7fa9ac6a2b70>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fa9ad267710>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 522}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-522/'>
               └ <function doc at 0x7fa9ad1288c8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 522}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-522/'>
           └ <function doc at 0x7fa9ad128840>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 522
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fa9af692080>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 522, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fa9b0846d08>
                   └ <django.db.models.manager.Manager object at 0x7fa9aed1c860>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-27 19:15:43.112 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f73691b4ea0>
    └ <Thread(Thread-151, started daemon 140133290465024)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f73691b4c80>
    └ <Thread(Thread-151, started daemon 140133290465024)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-151, started daemon 140133290465024)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-151, started daemon 140133290465024)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>>
    └ <Thread(Thread-151, started daemon 140133290465024)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 41120)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f736214e158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>
    │    │                   │        └ ('127.0.0.1', 41120)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f7360f4c7b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f73527c0780>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f7360f4c840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f73527c0780>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f7360f49d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f73527c0780>
    │       └ <function BaseHandler.run at 0x7f7360f45a60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f73582a60f0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f7360f45d90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f73582a60f0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f73582a60f0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f735abea710>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f73582a60f0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │    └ <function BaseHandler.get_response at 0x7f7360f7df28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f735abea710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-523/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f735abea710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7f735a086080>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0400>
               │           └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7f735a086080>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f735a086240>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0378>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f735a086240>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f735a086630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff02f0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f735a086630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f735a086ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0268>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f735a086ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f735a011048>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff01e0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f735a011048>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f735a011198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0158>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f735a011198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f735ac003c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff00d0>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f735ac003c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f735ac00320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0048>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f735ac00320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f735ac002e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359fdbf28>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f735ac002e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f735ac00128>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359fdbd08>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f735ac00128>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f735ac00160>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359fdbe18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f735ac00160>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7f735a01d8d0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               │           │    └ <function BaseHandler._get_response at 0x7f7359fdbd90>
               │           └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7f735a01d8d0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f735abea710>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 523}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-523/'>
               └ <function doc at 0x7f735aaaa8c8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 523}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-523/'>
           └ <function doc at 0x7f735aaaa840>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 523
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f7361053080>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 523, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f7362207d08>
                   └ <django.db.models.manager.Manager object at 0x7f73606dd8d0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-27 21:39:17.746 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f73691b4ea0>
    └ <Thread(Thread-338, started daemon 140133280499456)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f73691b4c80>
    └ <Thread(Thread-338, started daemon 140133280499456)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-338, started daemon 140133280499456)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-338, started daemon 140133280499456)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>>
    └ <Thread(Thread-338, started daemon 140133280499456)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 42166)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f736214e158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>
    │    │                   │        └ ('127.0.0.1', 42166)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f7360f4c7b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f735a027dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f7360f4c840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f735a027dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f7360f49d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f735a027dd8>
    │       └ <function BaseHandler.run at 0x7f7360f45a60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f7358ae7358>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f7360f45d90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f7358ae7358>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f7358ae7358>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f735abea710>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f7358ae7358>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │    └ <function BaseHandler.get_response at 0x7f7360f7df28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f735abea710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-790/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f735abea710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7f735a086080>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0400>
               │           └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7f735a086080>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f735a086240>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0378>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f735a086240>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f735a086630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff02f0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f735a086630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f735a086ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0268>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f735a086ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f735a011048>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff01e0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f735a011048>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f735a011198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0158>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f735a011198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f735ac003c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff00d0>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f735ac003c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f735ac00320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0048>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f735ac00320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f735ac002e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359fdbf28>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f735ac002e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f735ac00128>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359fdbd08>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f735ac00128>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f735ac00160>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359fdbe18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f735ac00160>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7f735a01d8d0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               │           │    └ <function BaseHandler._get_response at 0x7f7359fdbd90>
               │           └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7f735a01d8d0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f735abea710>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 790}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-790/'>
               └ <function doc at 0x7f735aaaa8c8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 790}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-790/'>
           └ <function doc at 0x7f735aaaa840>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 790
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f7361053080>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 790, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f7362207d08>
                   └ <django.db.models.manager.Manager object at 0x7f73606dd8d0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-27 23:47:22.011 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f73691b4ea0>
    └ <Thread(Thread-372, started daemon 140133280499456)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f73691b4c80>
    └ <Thread(Thread-372, started daemon 140133280499456)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-372, started daemon 140133280499456)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-372, started daemon 140133280499456)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>>
    └ <Thread(Thread-372, started daemon 140133280499456)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 42668)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f736214e158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>
    │    │                   │        └ ('127.0.0.1', 42668)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f7360f4c7b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f7358110c88>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f7360f4c840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f7358110c88>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f7360f49d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f735a0113c8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f7358110c88>
    │       └ <function BaseHandler.run at 0x7f7360f45a60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f7358ae7860>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f7360f45d90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f7358ae7860>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f7358ae7860>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f735abea710>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f7358ae7860>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │    └ <function BaseHandler.get_response at 0x7f7360f7df28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f735abea710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-537/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f735abea710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7f735a086080>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0400>
               │           └ <django.middleware.cache.UpdateCacheMiddleware object at 0x7f735a086080>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f735a086240>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0378>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f735a086240>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f735a086630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff02f0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f735a086630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f735a086ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0268>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f735a086ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f735a011048>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff01e0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f735a011048>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f735a011198>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0158>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f735a011198>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f735ac003c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff00d0>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f735ac003c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f735ac00320>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359ff0048>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f735ac00320>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f735ac002e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359fdbf28>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f735ac002e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f735ac00128>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359fdbd08>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f735ac00128>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f735ac00160>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f7359fdbe18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f735ac00160>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7f735a01d8d0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               │           │    └ <function BaseHandler._get_response at 0x7f7359fdbd90>
               │           └ <django.middleware.cache.FetchFromCacheMiddleware object at 0x7f735a01d8d0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f735abea710>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 537}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-537/'>
               └ <function doc at 0x7f735aaaa8c8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 537}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-537/'>
           └ <function doc at 0x7f735aaaa840>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 537
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f7361053080>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 537, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f7362207d08>
                   └ <django.db.models.manager.Manager object at 0x7f73606dd8d0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
