2021-08-13 11:33:39.823 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbe9f75e378>
    └ <Thread(Thread-798, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbe9f75e158>
    └ <Thread(Thread-798, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-798, started daemon 140456436430592)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-798, started daemon 140456436430592)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>>
    └ <Thread(Thread-798, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 35510)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbe99315e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │    │                   │        └ ('127.0.0.1', 35510)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbe983c1b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe9406f4a8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbe983c1bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe9406f4a8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbe983c10d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe9406f4a8>
    │       └ <function BaseHandler.run at 0x7fbe983b9d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe9442f160>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbe983be158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe9442f160>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe9442f160>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe9442f160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler.get_response at 0x7fbe98548840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562a60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955629d8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562950>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955628c8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562840>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955627b8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562730>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955626a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562620>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler._get_response at 0x7fbe95648b70>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 53}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <function doc at 0x7fbe95fa4598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 53}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-53/'>
           └ <function doc at 0x7fbe95fa4510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 53
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbe984d2048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 53, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbe993dd8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbe95735f28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-13 11:50:32.310 | ERROR    | app_doc.views:project_index:408 - 文集页访问异常
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbe9f75e378>
    └ <Thread(Thread-804, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbe9f75e158>
    └ <Thread(Thread-804, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-804, started daemon 140456436430592)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-804, started daemon 140456436430592)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>>
    └ <Thread(Thread-804, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 59376)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbe99315e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │    │                   │        └ ('127.0.0.1', 59376)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbe983c1b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe9442f160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbe983c1bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe9442f160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbe983c10d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe9442f160>
    │       └ <function BaseHandler.run at 0x7fbe983b9d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe955aa9b0>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbe983be158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe955aa9b0>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe955aa9b0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe955aa9b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-43/'>
               │    └ <function BaseHandler.get_response at 0x7fbe98548840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-43/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562a60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955629d8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562950>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955628c8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562840>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955627b8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562730>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955626a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562620>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-43/'>
               │    └ <function BaseHandler._get_response at 0x7fbe95648b70>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 43}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-43/'>
               └ <function check_headers.<locals>._inner at 0x7fbe95f9d488>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 43}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-43/'>
           └ <function check_headers.<locals>._inner at 0x7fbe95f9d400>

  File "/usr/local/projects/MrDoc/app_admin/decorators.py", line 43, in _inner
    return function(request, *args, **kwargs)
           │        │         │       └ {'pro_id': 43}
           │        │         └ ()
           │        └ <WSGIRequest: GET '/project-43/'>
           └ <function project_index at 0x7fbe95f9d378>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 339, in project_index
    project = Project.objects.get(id=int(pro_id))
              │       │                  └ 43
              │       └ <django.db.models.manager.ManagerDescriptor object at 0x7fbe984bca58>
              └ <class 'app_doc.models.Project'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 43}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbe993dd8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbe95735b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Project'
    │    │     └ <Options for Project>
    │    └ <class 'app_doc.models.Project'>
    └ <QuerySet [<Project: About>, <Project: Algorithm Notebook>, <Project: Common Commands>, <Project: Machine Learning>, <Project...

app_doc.models.Project.DoesNotExist: Project matching query does not exist.
2021-08-13 11:52:07.246 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-13_1129130.3451463128892627.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-13_1129130.3451463128892627.png?",)
2021-08-13 11:52:07.262 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-13_1146010.7831356227262808.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-13_1146010.7831356227262808.png?",)
2021-08-13 11:52:07.285 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-13_1151530.0821075316999722.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-13_1151530.0821075316999722.png?",)
2021-08-13 12:39:43.717 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbe9f75e378>
    └ <Thread(Thread-830, started daemon 140456411252480)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbe9f75e158>
    └ <Thread(Thread-830, started daemon 140456411252480)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-830, started daemon 140456411252480)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-830, started daemon 140456411252480)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>>
    └ <Thread(Thread-830, started daemon 140456411252480)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 48184)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbe99315e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │    │                   │        └ ('127.0.0.1', 48184)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbe983c1b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe955aa9b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbe983c1bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe955aa9b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbe983c10d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe955aa9b0>
    │       └ <function BaseHandler.run at 0x7fbe983b9d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe943424a8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbe983be158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe943424a8>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe943424a8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe943424a8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │    └ <function BaseHandler.get_response at 0x7fbe98548840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-289/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562a60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955629d8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562950>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955628c8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562840>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955627b8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562730>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955626a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562620>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │    └ <function BaseHandler._get_response at 0x7fbe95648b70>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 289}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <function doc at 0x7fbe95fa4598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 289}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-289/'>
           └ <function doc at 0x7fbe95fa4510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 289
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbe984d2048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 289, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbe993dd8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbe95735f28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-13 17:28:02.692 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbe9f75e378>
    └ <Thread(Thread-990, started daemon 140456419645184)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbe9f75e158>
    └ <Thread(Thread-990, started daemon 140456419645184)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-990, started daemon 140456419645184)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-990, started daemon 140456419645184)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>>
    └ <Thread(Thread-990, started daemon 140456419645184)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 44782)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbe99315e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │    │                   │        └ ('127.0.0.1', 44782)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbe983c1b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe9439e9b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbe983c1bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe9439e9b0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbe983c10d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe9439e9b0>
    │       └ <function BaseHandler.run at 0x7fbe983b9d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe945373c8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbe983be158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe945373c8>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe945373c8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe945373c8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               │    └ <function BaseHandler.get_response at 0x7fbe98548840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-183/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562a60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955629d8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562950>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955628c8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562840>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955627b8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562730>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955626a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562620>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               │    └ <function BaseHandler._get_response at 0x7fbe95648b70>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-183/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 183}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-183/'>
               └ <function doc at 0x7fbe95fa4598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 183}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-183/'>
           └ <function doc at 0x7fbe95fa4510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 183
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbe984d2048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 183, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbe993dd8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbe95735f28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-14 01:28:01.030 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbe9f75e378>
    └ <Thread(Thread-1169, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbe9f75e158>
    └ <Thread(Thread-1169, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1169, started daemon 140456436430592)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1169, started daemon 140456436430592)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>>
    └ <Thread(Thread-1169, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 43982)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbe99315e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │    │                   │        └ ('127.0.0.1', 43982)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbe983c1b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe943a43c8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbe983c1bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe943a43c8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbe983c10d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe943a43c8>
    │       └ <function BaseHandler.run at 0x7fbe983b9d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe9446bac8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbe983be158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe9446bac8>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe9446bac8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe9446bac8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               │    └ <function BaseHandler.get_response at 0x7fbe98548840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-9/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562a60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955629d8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562950>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955628c8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562840>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955627b8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562730>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955626a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562620>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               │    └ <function BaseHandler._get_response at 0x7fbe95648b70>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-9/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 9}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-9/'>
               └ <function doc at 0x7fbe95fa4598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 9}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-9/'>
           └ <function doc at 0x7fbe95fa4510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 9
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbe984d2048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 9, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbe993dd8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbe95735f28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-14 03:28:02.534 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbe9f75e378>
    └ <Thread(Thread-1200, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbe9f75e158>
    └ <Thread(Thread-1200, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1200, started daemon 140456436430592)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1200, started daemon 140456436430592)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>>
    └ <Thread(Thread-1200, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 40892)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbe99315e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │    │                   │        └ ('127.0.0.1', 40892)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbe983c1b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe8cb7de80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbe983c1bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe8cb7de80>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbe983c10d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe8cb7de80>
    │       └ <function BaseHandler.run at 0x7fbe983b9d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe8dfdb438>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbe983be158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe8dfdb438>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe8dfdb438>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe8dfdb438>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               │    └ <function BaseHandler.get_response at 0x7fbe98548840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-51/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562a60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955629d8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562950>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955628c8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562840>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955627b8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562730>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955626a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562620>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               │    └ <function BaseHandler._get_response at 0x7fbe95648b70>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-51/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 51}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-51/'>
               └ <function doc at 0x7fbe95fa4598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 51}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-51/'>
           └ <function doc at 0x7fbe95fa4510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 51
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbe984d2048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 51, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbe993dd8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbe95735f28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-14 06:59:30.544 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbe9f75e378>
    └ <Thread(Thread-1244, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbe9f75e158>
    └ <Thread(Thread-1244, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1244, started daemon 140456436430592)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1244, started daemon 140456436430592)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>>
    └ <Thread(Thread-1244, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 2962)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbe99315e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │    │                   │        └ ('127.0.0.1', 2962)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbe983c1b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe943426a0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbe983c1bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe943426a0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbe983c10d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe943426a0>
    │       └ <function BaseHandler.run at 0x7fbe983b9d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe94426f28>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbe983be158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe94426f28>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe94426f28>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe94426f28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │    └ <function BaseHandler.get_response at 0x7fbe98548840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-511/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562a60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955629d8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562950>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955628c8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562840>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955627b8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562730>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955626a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562620>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │    └ <function BaseHandler._get_response at 0x7fbe95648b70>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 511}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <function doc at 0x7fbe95fa4598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 511}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-511/'>
           └ <function doc at 0x7fbe95fa4510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 511
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbe984d2048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 511, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbe993dd8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbe95735f28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-14 08:15:26.783 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbe9f75e378>
    └ <Thread(Thread-1262, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbe9f75e158>
    └ <Thread(Thread-1262, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1262, started daemon 140456436430592)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1262, started daemon 140456436430592)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>>
    └ <Thread(Thread-1262, started daemon 140456436430592)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 19568)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbe99315e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │    │                   │        └ ('127.0.0.1', 19568)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbe983c1b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe943426a0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbe983c1bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe943426a0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbe983c10d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe943426a0>
    │       └ <function BaseHandler.run at 0x7fbe983b9d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe8cb6fb70>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbe983be158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe8cb6fb70>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe8cb6fb70>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe8cb6fb70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function BaseHandler.get_response at 0x7fbe98548840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562a60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955629d8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562950>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955628c8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562840>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955627b8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562730>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955626a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562620>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function BaseHandler._get_response at 0x7fbe95648b70>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 161}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <function doc at 0x7fbe95fa4598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 161}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-161/'>
           └ <function doc at 0x7fbe95fa4510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 161
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbe984d2048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 161, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbe993dd8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbe95735f28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
