2022-05-04 02:57:13.589 | ERROR    | app_doc.views:doc:1073 - 文集浏览出错
Traceback (most recent call last):
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fdc63436510>
    └ <Thread(Thread-2344, started daemon 140583666444032)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fdc634362f0>
    └ <Thread(Thread-2344, started daemon 140583666444032)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2344, started daemon 140583666444032)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2344, started daemon 140583666444032)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>>
    └ <Thread(Thread-2344, started daemon 140583666444032)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53530)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fdc5e2a5bf8>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │    │                   │        └ ('127.0.0.1', 53530)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fdc5d2a4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc54355748>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fdc5d2a4c80>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc54355748>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fdc5d2a4268>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc54355748>
    │       └ <function BaseHandler.run at 0x7fdc5d299f28>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc54657b70>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fdc5d2a02f0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc54657b70>
    │    │        │           │    └ {'LC_ALL': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc54657b70>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc54657b70>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               │    └ <function BaseHandler.get_response at 0x7fdc5d2e6488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-158/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549c80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549bf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549b70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549ae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549a60>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565499d8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549950>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565498c8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549840>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 35, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               │    └ <function BaseHandler._get_response at 0x7fdc56799048>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-158/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 158}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-158/'>
               └ <function doc at 0x7fdc57052950>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 158}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-158/'>
           └ <function doc at 0x7fdc570528c8>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1000, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 158
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fdc5d3ab1d0>
          └ <class 'app_doc.models.Doc'>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 158, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fdc5e36fae8>
                   └ <django.db.models.manager.Manager object at 0x7fdc56671da0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-05-04 03:44:51.951 | ERROR    | app_doc.views:doc:1073 - Collection browsing error
Traceback (most recent call last):
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fdc63436510>
    └ <Thread(Thread-2364, started daemon 140583666444032)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fdc634362f0>
    └ <Thread(Thread-2364, started daemon 140583666444032)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2364, started daemon 140583666444032)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2364, started daemon 140583666444032)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>>
    └ <Thread(Thread-2364, started daemon 140583666444032)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53590)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fdc5e2a5bf8>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │    │                   │        └ ('127.0.0.1', 53590)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fdc5d2a4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc5463a438>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fdc5d2a4c80>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc5463a438>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fdc5d2a4268>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fdc5ea0b0b8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fdc5463a438>
    │       └ <function BaseHandler.run at 0x7fdc5d299f28>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc5467a710>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fdc5d2a02f0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc5467a710>
    │    │        │           │    └ {'LC_ALL': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc5467a710>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fdc5467a710>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function BaseHandler.get_response at 0x7fdc5d2e6488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549c80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549bf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fdc5657b390>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549b70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fdc5657bfd0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549ae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fdc5657bb70>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549a60>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fdc5712b320>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565499d8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fdc5712b2b0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549950>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fdc5712b2e8>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc565498c8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fdc56587940>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fdc56549840>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fdc56587668>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 35, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function BaseHandler._get_response at 0x7fdc56799048>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fdc57d55c50>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fdc571192b0>>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 738}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <function doc at 0x7fdc57052950>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 738}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-738/'>
           └ <function doc at 0x7fdc570528c8>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1000, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 738
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fdc5d3ab1d0>
          └ <class 'app_doc.models.Doc'>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 738, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fdc5e36fae8>
                   └ <django.db.models.manager.Manager object at 0x7fdc56671da0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
