2022-05-31 19:45:27.801 | ERROR    | app_doc.views:project_index:460 - 文集页访问异常
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff0f0180ea0>
    └ <Thread(Thread-2071, started daemon 140672523548416)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff0f0180c80>
    └ <Thread(Thread-2071, started daemon 140672523548416)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2071, started daemon 140672523548416)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2071, started daemon 140672523548416)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7ff0ea05ee48>>
    └ <Thread(Thread-2071, started daemon 140672523548416)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 44564)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7ff0e911e0d0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7ff0ea05ee48>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7ff0ea05ee48>
    │    │                   │        └ ('127.0.0.1', 44564)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7ff0ea05ee48>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7ff0e7f0ae18>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7ff0de7bbcf8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7ff0e7f0aea0>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7ff0de7bbcf8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7ff0e7f0a400>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7ff0ea05ee48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7ff0de7bbcf8>
    │       └ <function BaseHandler.run at 0x7ff0e7f07158>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7ff0de0ad320>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7ff0e7f07488>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7ff0de0ad320>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7ff0de0ad320>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7ff0e5dc8080>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7ff0de0ad320>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-54/'>
               │    └ <function BaseHandler.get_response at 0x7ff0e7f4d620>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7ff0e5dc8080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-54/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7ff0e51d0048>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7ff0e5dc8080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7ff0e51ee898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7ff0e51bcf28>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7ff0e51ee898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7ff0e51fd2e8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7ff0e51bcea0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7ff0e51fd2e8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7ff0e51fd128>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7ff0e51bce18>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7ff0e51fd128>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7ff0e5dbef60>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7ff0e51bcd90>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7ff0e5dbef60>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7ff0e5dbeef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7ff0e51bcd08>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7ff0e5dbeef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7ff0e5dbef98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7ff0e51bcc80>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7ff0e5dbef98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7ff0e5dace10>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7ff0e51bcbf8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7ff0e5dace10>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7ff0e5dacf98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7ff0e51bcb70>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7ff0e5dacf98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7ff0e52077f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7ff0e51bcae8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7ff0e52077f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7ff0e5207208>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-54/'>
               │    └ <function BaseHandler._get_response at 0x7ff0e51a80d0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7ff0e5207208>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7ff0e5dc8080>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 54}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-54/'>
               └ <function check_headers.<locals>._inner at 0x7ff0e5c6b7b8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 54}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-54/'>
           └ <function check_headers.<locals>._inner at 0x7ff0e5c6b730>

  File "/usr/local/projects/MrDoc/app_admin/decorators.py", line 43, in _inner
    return function(request, *args, **kwargs)
           │        │         │       └ {'pro_id': 54}
           │        │         └ ()
           │        └ <WSGIRequest: GET '/project-54/'>
           └ <function project_index at 0x7ff0e5c6b6a8>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 391, in project_index
    project = Project.objects.get(id=int(pro_id))
              │       │                  └ 54
              │       └ <django.db.models.manager.ManagerDescriptor object at 0x7ff0e8003d30>
              └ <class 'app_doc.models.Project'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 54}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7ff0e91d7c80>
                   └ <django.db.models.manager.Manager object at 0x7ff0e7f08630>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Project'
    │    │     └ <Options for Project>
    │    └ <class 'app_doc.models.Project'>
    └ <QuerySet [<Project: About>, <Project: Algorithm Notebook>, <Project: Common Commands>, <Project: Machine Learning>, <Project...

app_doc.models.Project.DoesNotExist: Project matching query does not exist.
2022-05-31 20:58:52.935 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb69a830ea0>
    └ <Thread(Thread-103, started daemon 140421981017856)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb69a830c80>
    └ <Thread(Thread-103, started daemon 140421981017856)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-103, started daemon 140421981017856)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-103, started daemon 140421981017856)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>>
    └ <Thread(Thread-103, started daemon 140421981017856)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 46442)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb6937ce0d0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
    │    │                   │        └ ('127.0.0.1', 46442)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb6925bbe18>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb6899ed278>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb6925bbea0>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb6899ed278>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb6925bb400>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb6899ed278>
    │       └ <function BaseHandler.run at 0x7fb6925b8158>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb68883a588>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb6925b8488>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb68883a588>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb68883a588>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb68883a588>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function BaseHandler.get_response at 0x7fb6925fe620>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b1158>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb68b883278>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b10d0>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb68b883278>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb692d0dc88>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b1048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb692d0dc88>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb68b94b9b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aaf28>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb68b94b9b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb68b94b3c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aaea0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb68b94b3c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fb69046ef60>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aae18>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fb69046ef60>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb69046eef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aad90>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb69046eef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb69046ef98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aad08>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb69046ef98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb69045de48>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aac80>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb69045de48>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb69045dfd0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8d4158>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb69045dfd0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb691035be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function BaseHandler._get_response at 0x7fb68b8d41e0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb691035be0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 323}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <function doc at 0x7fb6903228c8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 323}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-323/'>
           └ <function doc at 0x7fb690322840>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 323
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fb6926c5240>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 323, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fb693887c80>
                   └ <django.db.models.manager.Manager object at 0x7fb6918c4358>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-01 02:28:43.931 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb69a830ea0>
    └ <Thread(Thread-285, started daemon 140421968692992)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb69a830c80>
    └ <Thread(Thread-285, started daemon 140421968692992)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-285, started daemon 140421968692992)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-285, started daemon 140421968692992)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>>
    └ <Thread(Thread-285, started daemon 140421968692992)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 47064)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb6937ce0d0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
    │    │                   │        └ ('127.0.0.1', 47064)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb6925bbe18>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb6899cb470>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb6925bbea0>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb6899cb470>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb6925bb400>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb6899cb470>
    │       └ <function BaseHandler.run at 0x7fb6925b8158>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb6886ba780>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb6925b8488>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb6886ba780>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb6886ba780>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb6886ba780>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function BaseHandler.get_response at 0x7fb6925fe620>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b1158>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb68b883278>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b10d0>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb68b883278>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb692d0dc88>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b1048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb692d0dc88>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb68b94b9b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aaf28>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb68b94b9b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb68b94b3c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aaea0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb68b94b3c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fb69046ef60>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aae18>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fb69046ef60>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb69046eef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aad90>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb69046eef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb69046ef98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aad08>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb69046ef98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb69045de48>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aac80>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb69045de48>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb69045dfd0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8d4158>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb69045dfd0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb691035be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function BaseHandler._get_response at 0x7fb68b8d41e0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb691035be0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 343}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <function doc at 0x7fb6903228c8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 343}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-343/'>
           └ <function doc at 0x7fb690322840>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 343
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fb6926c5240>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 343, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fb693887c80>
                   └ <django.db.models.manager.Manager object at 0x7fb6918c4358>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-01 08:32:52.821 | ERROR    | app_doc.views:project_index:460 - 文集页访问异常
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb69a830ea0>
    └ <Thread(Thread-393, started daemon 140421960300288)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb69a830c80>
    └ <Thread(Thread-393, started daemon 140421960300288)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-393, started daemon 140421960300288)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-393, started daemon 140421960300288)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>>
    └ <Thread(Thread-393, started daemon 140421960300288)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 47458)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb6937ce0d0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
    │    │                   │        └ ('127.0.0.1', 47458)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb6925bbe18>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb688716358>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb6925bbea0>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb688716358>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb6925bb400>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb688716358>
    │       └ <function BaseHandler.run at 0x7fb6925b8158>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb688716048>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb6925b8488>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb688716048>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb688716048>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb688716048>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-54/'>
               │    └ <function BaseHandler.get_response at 0x7fb6925fe620>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-54/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b1158>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb68b883278>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b10d0>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb68b883278>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb692d0dc88>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b1048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb692d0dc88>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb68b94b9b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aaf28>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb68b94b9b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb68b94b3c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aaea0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb68b94b3c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fb69046ef60>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aae18>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fb69046ef60>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb69046eef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aad90>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb69046eef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb69046ef98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aad08>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb69046ef98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb69045de48>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aac80>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb69045de48>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb69045dfd0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-54/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8d4158>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb69045dfd0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb691035be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-54/'>
               │    └ <function BaseHandler._get_response at 0x7fb68b8d41e0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb691035be0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-54/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 54}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-54/'>
               └ <function check_headers.<locals>._inner at 0x7fb69031d7b8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 54}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-54/'>
           └ <function check_headers.<locals>._inner at 0x7fb69031d730>

  File "/usr/local/projects/MrDoc/app_admin/decorators.py", line 43, in _inner
    return function(request, *args, **kwargs)
           │        │         │       └ {'pro_id': 54}
           │        │         └ ()
           │        └ <WSGIRequest: GET '/project-54/'>
           └ <function project_index at 0x7fb69031d6a8>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 391, in project_index
    project = Project.objects.get(id=int(pro_id))
              │       │                  └ 54
              │       └ <django.db.models.manager.ManagerDescriptor object at 0x7fb6926b3d30>
              └ <class 'app_doc.models.Project'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 54}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fb693887c80>
                   └ <django.db.models.manager.Manager object at 0x7fb6925b9668>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Project'
    │    │     └ <Options for Project>
    │    └ <class 'app_doc.models.Project'>
    └ <QuerySet [<Project: About>, <Project: Algorithm Notebook>, <Project: Common Commands>, <Project: Machine Learning>, <Project...

app_doc.models.Project.DoesNotExist: Project matching query does not exist.
2022-06-01 14:48:27.657 | ERROR    | app_doc.views:diff_doc:1662 - 文档历史版本页面访问出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb69a830ea0>
    └ <Thread(Thread-1033, started daemon 140421968692992)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb69a830c80>
    └ <Thread(Thread-1033, started daemon 140421968692992)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1033, started daemon 140421968692992)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1033, started daemon 140421968692992)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>>
    └ <Thread(Thread-1033, started daemon 140421968692992)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 48986)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb6937ce0d0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
    │    │                   │        └ ('127.0.0.1', 48986)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb6925bbe18>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb68864fe10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb6925bbea0>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb68864fe10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb6925bb400>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb68864fe10>
    │       └ <function BaseHandler.run at 0x7fb6925b8158>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb688710828>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb6925b8488>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb688710828>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb688710828>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb688710828>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │    └ <function BaseHandler.get_response at 0x7fb6925fe620>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b1158>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb68b883278>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b10d0>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb68b883278>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb692d0dc88>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b1048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb692d0dc88>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb68b94b9b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aaf28>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb68b94b9b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb68b94b3c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aaea0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb68b94b3c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fb69046ef60>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aae18>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fb69046ef60>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb69046eef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aad90>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb69046eef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb69046ef98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aad08>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb69046ef98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb69045de48>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aac80>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb69045de48>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb69045dfd0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8d4158>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb69045dfd0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb691035be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │    └ <function BaseHandler._get_response at 0x7fb68b8d41e0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb691035be0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'doc_id': 925, 'his_id': 3182}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <function diff_doc at 0x7fb6903278c8>

  File "/usr/local/lib64/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           │         │         │       └ {'doc_id': 925, 'his_id': 3182}
           │         │         └ ()
           │         └ <WSGIRequest: GET '/diff_doc/925-3182/'>
           └ <function diff_doc at 0x7fb6903279d8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'doc_id': 925, 'his_id': 3182}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/diff_doc/925-3182/'>
           └ <function diff_doc at 0x7fb690327950>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1652, in diff_doc
    if (request.user == doc.create_user) or (pro_colla[0].role == 1) or (request.user.is_superuser):
        │       │       │   │                │                           │       └ <SimpleLazyObject: <User: grayson>>
        │       │       │   │                │                           └ <WSGIRequest: GET '/diff_doc/925-3182/'>
        │       │       │   │                └ <QuerySet []>
        │       │       │   └ <django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x7fb6926b6d68>
        │       │       └ <Doc: 多态>
        │       └ <SimpleLazyObject: <User: grayson>>
        └ <WSGIRequest: GET '/diff_doc/925-3182/'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 309, in __getitem__
    return qs._result_cache[0]
           │  └ []
           └ <QuerySet []>

IndexError: list index out of range
2022-06-01 14:48:31.266 | ERROR    | app_doc.views:diff_doc:1662 - 文档历史版本页面访问出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb69a830ea0>
    └ <Thread(Thread-1035, started daemon 140421968692992)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb69a830c80>
    └ <Thread(Thread-1035, started daemon 140421968692992)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1035, started daemon 140421968692992)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1035, started daemon 140421968692992)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>>
    └ <Thread(Thread-1035, started daemon 140421968692992)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 48990)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb6937ce0d0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
    │    │                   │        └ ('127.0.0.1', 48990)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb6925bbe18>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb6887c47f0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb6925bbea0>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb6887c47f0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb6925bb400>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb69470fe48>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb6887c47f0>
    │       └ <function BaseHandler.run at 0x7fb6925b8158>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb6885c1390>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb6925b8488>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb6885c1390>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb6885c1390>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb6885c1390>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │    └ <function BaseHandler.get_response at 0x7fb6925fe620>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b1158>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb68b883278>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b10d0>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb68b883278>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb692d0dc88>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8b1048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb692d0dc88>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb68b94b9b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aaf28>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb68b94b9b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb68b94b3c8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aaea0>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb68b94b3c8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fb69046ef60>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aae18>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fb69046ef60>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb69046eef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aad90>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb69046eef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb69046ef98>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aad08>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb69046ef98>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb69045de48>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8aac80>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb69045de48>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb69045dfd0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb68b8d4158>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb69045dfd0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb691035be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               │    └ <function BaseHandler._get_response at 0x7fb68b8d41e0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb691035be0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb690479080>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'doc_id': 925, 'his_id': 3182}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/diff_doc/925-3182/'>
               └ <function diff_doc at 0x7fb6903278c8>

  File "/usr/local/lib64/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           │         │         │       └ {'doc_id': 925, 'his_id': 3182}
           │         │         └ ()
           │         └ <WSGIRequest: GET '/diff_doc/925-3182/'>
           └ <function diff_doc at 0x7fb6903279d8>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'doc_id': 925, 'his_id': 3182}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/diff_doc/925-3182/'>
           └ <function diff_doc at 0x7fb690327950>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1652, in diff_doc
    if (request.user == doc.create_user) or (pro_colla[0].role == 1) or (request.user.is_superuser):
        │       │       │   │                │                           │       └ <SimpleLazyObject: <User: grayson>>
        │       │       │   │                │                           └ <WSGIRequest: GET '/diff_doc/925-3182/'>
        │       │       │   │                └ <QuerySet []>
        │       │       │   └ <django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x7fb6926b6d68>
        │       │       └ <Doc: 多态>
        │       └ <SimpleLazyObject: <User: grayson>>
        └ <WSGIRequest: GET '/diff_doc/925-3182/'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 309, in __getitem__
    return qs._result_cache[0]
           │  └ []
           └ <QuerySet []>

IndexError: list index out of range
2022-06-01 19:33:44.553 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202206/2022-06-01_1709220.7318460992745337.png': No schema supplied. Perhaps you meant http:///media/202206/2022-06-01_1709220.7318460992745337.png?",)
2022-06-01 19:33:54.036 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-28_1148300.050953602887815364.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-28_1148300.050953602887815364.png?",)
2022-06-01 19:33:54.048 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-28_1151150.4816085587647606.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-28_1151150.4816085587647606.png?",)
2022-06-01 19:33:54.057 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-28_1156350.7073084618631299.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-28_1156350.7073084618631299.png?",)
2022-06-01 19:33:54.067 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-29_1134020.139742301000497.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-29_1134020.139742301000497.png?",)
2022-06-01 19:33:54.077 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-29_1610300.1202024267313998.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-29_1610300.1202024267313998.png?",)
2022-06-01 19:33:54.087 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-29_1647180.7275877842219161.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-29_1647180.7275877842219161.png?",)
2022-06-01 19:33:54.096 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-27_102456_404830.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-27_102456_404830.png?",)
2022-06-01 19:33:54.105 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-27_103001_656451.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-27_103001_656451.png?",)
2022-06-01 19:33:54.113 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-30_1622060.7070800430543429.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-30_1622060.7070800430543429.png?",)
2022-06-01 19:33:54.122 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202206/2022-06-01_1933440.29035427711482786.png': No schema supplied. Perhaps you meant http:///media/202206/2022-06-01_1933440.29035427711482786.png?",)
2022-06-01 19:33:54.134 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202206/2022-06-01_1709220.7318460992745337.png': No schema supplied. Perhaps you meant http:///media/202206/2022-06-01_1709220.7318460992745337.png?",)
2022-06-01 19:35:25.411 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-29_1134020.139742301000497.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-29_1134020.139742301000497.png?",)
2022-06-01 19:35:25.420 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-28_1148300.050953602887815364.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-28_1148300.050953602887815364.png?",)
2022-06-01 19:35:25.431 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-29_1610300.1202024267313998.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-29_1610300.1202024267313998.png?",)
2022-06-01 19:35:25.439 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-27_103001_656451.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-27_103001_656451.png?",)
2022-06-01 19:35:25.449 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-30_1622060.7070800430543429.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-30_1622060.7070800430543429.png?",)
2022-06-01 19:35:25.458 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202206/2022-06-01_1933440.29035427711482786.png': No schema supplied. Perhaps you meant http:///media/202206/2022-06-01_1933440.29035427711482786.png?",)
2022-06-01 19:35:25.467 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202206/2022-06-01_1709220.7318460992745337.png': No schema supplied. Perhaps you meant http:///media/202206/2022-06-01_1709220.7318460992745337.png?",)
2022-06-01 19:35:25.477 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-28_1156350.7073084618631299.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-28_1156350.7073084618631299.png?",)
2022-06-01 19:35:25.488 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-28_1151150.4816085587647606.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-28_1151150.4816085587647606.png?",)
2022-06-01 19:35:25.499 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-27_102456_404830.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-27_102456_404830.png?",)
2022-06-01 19:35:25.510 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-29_1647180.7275877842219161.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-29_1647180.7275877842219161.png?",)
2022-06-01 19:39:21.520 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-28_1148300.050953602887815364.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-28_1148300.050953602887815364.png?",)
2022-06-01 19:39:21.531 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202206/2022-06-01_1938090.4511449929817345.png': No schema supplied. Perhaps you meant http:///media/202206/2022-06-01_1938090.4511449929817345.png?",)
2022-06-01 19:39:21.539 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202206/2022-06-01_1937230.6582568592635254.png': No schema supplied. Perhaps you meant http:///media/202206/2022-06-01_1937230.6582568592635254.png?",)
2022-06-01 19:39:21.548 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-29_1610300.1202024267313998.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-29_1610300.1202024267313998.png?",)
2022-06-01 19:39:21.556 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-27_102456_404830.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-27_102456_404830.png?",)
2022-06-01 19:39:21.564 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202206/2022-06-01_1933440.29035427711482786.png': No schema supplied. Perhaps you meant http:///media/202206/2022-06-01_1933440.29035427711482786.png?",)
2022-06-01 19:39:21.572 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-27_103001_656451.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-27_103001_656451.png?",)
2022-06-01 19:39:21.581 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-29_1134020.139742301000497.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-29_1134020.139742301000497.png?",)
2022-06-01 19:39:21.589 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-30_1622060.7070800430543429.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-30_1622060.7070800430543429.png?",)
2022-06-01 19:39:21.597 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202206/2022-06-01_1709220.7318460992745337.png': No schema supplied. Perhaps you meant http:///media/202206/2022-06-01_1709220.7318460992745337.png?",)
2022-06-01 19:39:21.605 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-28_1151150.4816085587647606.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-28_1151150.4816085587647606.png?",)
2022-06-01 19:39:21.613 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-28_1156350.7073084618631299.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-28_1156350.7073084618631299.png?",)
2022-06-01 19:39:22.553 | ERROR    | app_doc.util_upload_img:url_img_upload:321 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202205/2022-05-29_1647180.7275877842219161.png': No schema supplied. Perhaps you meant http:///media/202205/2022-05-29_1647180.7275877842219161.png?",)
