2021-08-14 11:15:27.354 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbe9f75e378>
    └ <Thread(Thread-1388, started daemon 140456419645184)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbe9f75e158>
    └ <Thread(Thread-1388, started daemon 140456419645184)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1388, started daemon 140456419645184)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1388, started daemon 140456419645184)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>>
    └ <Thread(Thread-1388, started daemon 140456419645184)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 11588)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbe99315e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │    │                   │        └ ('127.0.0.1', 11588)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbe983c1b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe945fcf28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbe983c1bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe945fcf28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbe983c10d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe945fcf28>
    │       └ <function BaseHandler.run at 0x7fbe983b9d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe943f1b00>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbe983be158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe943f1b00>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe943f1b00>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe943f1b00>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler.get_response at 0x7fbe98548840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562a60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955629d8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562950>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955628c8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562840>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955627b8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562730>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955626a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562620>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler._get_response at 0x7fbe95648b70>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 53}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <function doc at 0x7fbe95fa4598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 53}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-53/'>
           └ <function doc at 0x7fbe95fa4510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 53
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbe984d2048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 53, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbe993dd8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbe95735f28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-14 11:45:26.010 | ERROR    | app_doc.views:project_index:408 - 文集页访问异常
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbe9f75e378>
    └ <Thread(Thread-1397, started daemon 140456419645184)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbe9f75e158>
    └ <Thread(Thread-1397, started daemon 140456419645184)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1397, started daemon 140456419645184)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1397, started daemon 140456419645184)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>>
    └ <Thread(Thread-1397, started daemon 140456419645184)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 24672)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbe99315e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │    │                   │        └ ('127.0.0.1', 24672)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbe983c1b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe8df093c8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbe983c1bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe8df093c8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbe983c10d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe8df093c8>
    │       └ <function BaseHandler.run at 0x7fbe983b9d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe945e7240>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbe983be158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe945e7240>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe945e7240>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe945e7240>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-43/'>
               │    └ <function BaseHandler.get_response at 0x7fbe98548840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-43/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562a60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955629d8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562950>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955628c8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562840>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955627b8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562730>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955626a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562620>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-43/'>
               │    └ <function BaseHandler._get_response at 0x7fbe95648b70>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 43}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-43/'>
               └ <function check_headers.<locals>._inner at 0x7fbe95f9d488>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 43}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-43/'>
           └ <function check_headers.<locals>._inner at 0x7fbe95f9d400>

  File "/usr/local/projects/MrDoc/app_admin/decorators.py", line 43, in _inner
    return function(request, *args, **kwargs)
           │        │         │       └ {'pro_id': 43}
           │        │         └ ()
           │        └ <WSGIRequest: GET '/project-43/'>
           └ <function project_index at 0x7fbe95f9d378>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 339, in project_index
    project = Project.objects.get(id=int(pro_id))
              │       │                  └ 43
              │       └ <django.db.models.manager.ManagerDescriptor object at 0x7fbe984bca58>
              └ <class 'app_doc.models.Project'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 43}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbe993dd8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbe95735b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Project'
    │    │     └ <Options for Project>
    │    └ <class 'app_doc.models.Project'>
    └ <QuerySet [<Project: About>, <Project: Algorithm Notebook>, <Project: Common Commands>, <Project: Machine Learning>, <Project...

app_doc.models.Project.DoesNotExist: Project matching query does not exist.
2021-08-14 13:20:26.845 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbe9f75e378>
    └ <Thread(Thread-1417, started daemon 140456419645184)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbe9f75e158>
    └ <Thread(Thread-1417, started daemon 140456419645184)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1417, started daemon 140456419645184)>
    │    │        │    └ (<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1417, started daemon 140456419645184)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>>
    └ <Thread(Thread-1417, started daemon 140456419645184)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 52674)
    │    │              └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fbe99315e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │    │                   │        └ ('127.0.0.1', 52674)
    │    │                   └ <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fbe983c1b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe945373c8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fbe983c1bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe945373c8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fbe983c10d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fbe99808eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fbe945373c8>
    │       └ <function BaseHandler.run at 0x7fbe983b9d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe943f1358>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fbe983be158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe943f1358>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe943f1358>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fbe943f1358>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │    └ <function BaseHandler.get_response at 0x7fbe98548840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-289/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562a60>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955629d8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fbe956132e8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562950>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fbe95613390>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955628c8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fbe95613550>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562840>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fbe960f4b70>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955627b8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fbe960f4ba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562730>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fbe960f4c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe955626a8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fbe960f4208>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fbe95562620>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fbe960f4b38>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               │    └ <function BaseHandler._get_response at 0x7fbe95648b70>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fbe96d94be0>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fbe96d7fc50>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 289}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-289/'>
               └ <function doc at 0x7fbe95fa4598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 289}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-289/'>
           └ <function doc at 0x7fbe95fa4510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 289
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fbe984d2048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 289, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fbe993dd8c8>
                   └ <django.db.models.manager.Manager object at 0x7fbe95735f28>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-14 15:37:49.024 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1530140.20370258757518722.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1530140.20370258757518722.png?",)
2021-08-14 16:31:54.931 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1108160.6497700033512185.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1108160.6497700033512185.png?",)
2021-08-14 16:31:54.945 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1619390.3362120864888013.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1619390.3362120864888013.png?",)
2021-08-14 16:31:54.963 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1537490.10829876826260476.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1537490.10829876826260476.png?",)
2021-08-14 16:31:54.979 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1607460.7323622817394279.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1607460.7323622817394279.png?",)
2021-08-14 16:31:54.989 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1530140.20370258757518722.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1530140.20370258757518722.png?",)
2021-08-14 17:46:30.562 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1530140.20370258757518722.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1530140.20370258757518722.png?",)
2021-08-14 17:46:30.571 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1108160.6497700033512185.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1108160.6497700033512185.png?",)
2021-08-14 17:46:30.589 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1537490.10829876826260476.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1537490.10829876826260476.png?",)
2021-08-14 17:46:30.700 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1607460.7323622817394279.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1607460.7323622817394279.png?",)
2021-08-14 17:46:30.719 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1619390.3362120864888013.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1619390.3362120864888013.png?",)
2021-08-14 17:46:30.730 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1651100.4159073776917006.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1651100.4159073776917006.png?",)
2021-08-14 17:46:30.740 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-14_1726200.9675617428079062.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-14_1726200.9675617428079062.png?",)
2021-08-14 21:58:39.391 | ERROR    | app_doc.views:modify_doc:1239 - 修改文档异常
Traceback (most recent call last):
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           │    │      │       │    └ [751, '## 1 前言\n\n1. 我们所熟悉的 DFS（深度优先搜索）问题通常是在树或者图结构上进行的，而我们今天要讨论的 DFS 问题，是在一种【网格】结构中进行的，**岛屿问题是这类网格 DFS 问题的典型代表**。\n2. 网格结构遍历...
           │    │      │       └ 'INSERT INTO "app_doc_dochistory" ("doc_id", "pre_content", "create_user_id", "create_time") VALUES (%s, %s, %s, %s)'
           │    │      └ <function SQLiteCursorWrapper.execute at 0x7fbe985432f0>
           │    └ <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x7fbe8dfca4c8>
           └ <django.db.backends.utils.CursorWrapper object at 0x7fbe8dfeb390>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
           │        │      │       │     │      └ [751, '## 1 前言\n\n1. 我们所熟悉的 DFS（深度优先搜索）问题通常是在树或者图结构上进行的，而我们今天要讨论的 DFS 问题，是在一种【网格】结构中进行的，**岛屿问题是这类网格 DFS 问题的典型代表**。\n2. 网格结构遍历...
           │        │      │       │     └ 'INSERT INTO "app_doc_dochistory" ("doc_id", "pre_content", "create_user_id", "create_time") VALUES (?, ?, ?, ?)'
           │        │      │       └ <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x7fbe8dfca4c8>
           │        │      └ <method 'execute' of 'sqlite3.Cursor' objects>
           │        └ <class 'sqlite3.Cursor'>
           └ <module 'sqlite3.dbapi2' from '/root/.pyenv/versions/3.6.8/li2021-08-15 08:00:18.784 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7faa5e74a378>
    └ <Thread(Thread-136, started daemon 140369440757504)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7faa5e74a158>
    └ <Thread(Thread-136, started daemon 140369440757504)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-136, started daemon 140369440757504)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-136, started daemon 140369440757504)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7faa587f4eb8>>
    └ <Thread(Thread-136, started daemon 140369440757504)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 20980)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7faa58301e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7faa587f4eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7faa587f4eb8>
    │    │                   │        └ ('127.0.0.1', 20980)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7faa587f4eb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7faa573adb70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7faa5410f0b8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7faa573adbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7faa5410f0b8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7faa573ad0d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7faa587f4eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7faa5410f0b8>
    │       └ <function BaseHandler.run at 0x7faa573a4d90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7faa58e96278>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7faa573aa158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7faa58e96278>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7faa58e96278>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7faa55d87e10>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7faa58e96278>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               │    └ <function BaseHandler.get_response at 0x7faa57534840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7faa55d87e10>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-513/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7faa54666ea0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7faa55d87e10>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7faa546ba0f0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7faa54666e18>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7faa546ba0f0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7faa546badd8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7faa54666d90>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7faa546badd8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7faa54662208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7faa5475fb70>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7faa54662208>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7faa550e2ba8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7faa5475fae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7faa550e2ba8>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7faa550e2c50>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7faa5475fc80>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7faa550e2c50>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7faa550e2320>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7faa5475f8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7faa550e2320>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7faa546c8a90>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7faa5461da60>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7faa546c8a90>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7faa546c8be0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7faa5461d7b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7faa546c8be0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7faa55366fd0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               │    └ <function BaseHandler._get_response at 0x7faa5461d950>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7faa55366fd0>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-513/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7faa55d87e10>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 513}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-513/'>
               └ <function doc at 0x7faa54f93598>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 513}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-513/'>
           └ <function doc at 0x7faa54f93510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 513
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7faa574be048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 513, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7faa583c98c8>
                   └ <django.db.models.manager.Manager object at 0x7faa5471c7b8>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
