2022-07-07 13:48:40.671 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe32ef6d048>
    └ <Thread(Thread-8538, started daemon 140613124404992)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe32ef6cd90>
    └ <Thread(Thread-8538, started daemon 140613124404992)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-8538, started daemon 140613124404992)>
    │    │        │    └ (<socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-8538, started daemon 140613124404992)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>>
    └ <Thread(Thread-8538, started daemon 140613124404992)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53898)
    │    │              └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe327f05268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │    │                   │        └ ('127.0.0.1', 53898)
    │    │                   └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe326d037b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe327c3b278>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe326d03840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe327c3b278>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe326d01d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe327c3b278>
    │       └ <function BaseHandler.run at 0x7fe326cffa60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe327c3b7b8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe326cffd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe327c3b7b8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe327c3b7b8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe327c3b7b8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               │    └ <function BaseHandler.get_response at 0x7fe326d33f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-46/doc-839/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ac80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9abf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ab70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aa60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a9d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               │    └ <function BaseHandler._get_response at 0x7fe31fffce18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-46/doc-839/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 46, 'doc_id': 839}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-46/doc-839/'>
               └ <function doc at 0x7fe324a4e1e0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 46, 'doc_id': 839}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-46/doc-839/'>
           └ <function doc at 0x7fe324a4e158>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 839
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe326e04c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 839, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe327fbfe18>
                   └ <django.db.models.manager.Manager object at 0x7fe3240f1278>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-07 20:10:18.937 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe32ef6d048>
    └ <Thread(Thread-9474, started daemon 140613116012288)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe32ef6cd90>
    └ <Thread(Thread-9474, started daemon 140613116012288)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-9474, started daemon 140613116012288)>
    │    │        │    └ (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-9474, started daemon 140613116012288)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>>
    └ <Thread(Thread-9474, started daemon 140613116012288)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 56720)
    │    │              └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe327f05268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │    │                   │        └ ('127.0.0.1', 56720)
    │    │                   └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe326d037b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31ead5cf8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe326d03840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31ead5cf8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe326d01d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31ead5cf8>
    │       └ <function BaseHandler.run at 0x7fe326cffa60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe327c1fda0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe326cffd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe327c1fda0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe327c1fda0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe327c1fda0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function BaseHandler.get_response at 0x7fe326d33f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ac80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9abf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ab70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aa60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a9d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function BaseHandler._get_response at 0x7fe31fffce18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 26, 'doc_id': 306}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <function doc at 0x7fe324a4e1e0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 26, 'doc_id': 306}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-26/doc-306/'>
           └ <function doc at 0x7fe324a4e158>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 306
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe326e04c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 306, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe327fbfe18>
                   └ <django.db.models.manager.Manager object at 0x7fe3240f1278>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-07 22:37:21.424 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe32ef6d048>
    └ <Thread(Thread-9498, started daemon 140613116012288)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe32ef6cd90>
    └ <Thread(Thread-9498, started daemon 140613116012288)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-9498, started daemon 140613116012288)>
    │    │        │    └ (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-9498, started daemon 140613116012288)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>>
    └ <Thread(Thread-9498, started daemon 140613116012288)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 57166)
    │    │              └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fe327f05268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │    │                   │        └ ('127.0.0.1', 57166)
    │    │                   └ <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fe326d037b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31e107e80>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fe326d03840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31e107e80>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fe326d01d08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fe3283d40f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fe31e107e80>
    │       └ <function BaseHandler.run at 0x7fe326cffa60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe30ecbe2b0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fe326cffd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fe30ecbe2b0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fe30ecbe2b0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fe30ecbe2b0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │    └ <function BaseHandler.get_response at 0x7fe326d33f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-732/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad90>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ad08>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fe31ffc3a20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ac80>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fe31ffc3c50>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9abf8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fe31ffc3ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9ab70>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7fe31ffcfa20>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fe324ba2630>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9aa60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fe324ba24e0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a9d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fe324ba2588>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fe324ba2550>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fe31ff9a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fe324ba2438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               │    └ <function BaseHandler._get_response at 0x7fe31fffce18>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fe324b926a0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fe31ffde128>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 732}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-732/'>
               └ <function doc at 0x7fe324a4e1e0>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 732}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-732/'>
           └ <function doc at 0x7fe324a4e158>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 732
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fe326e04c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 732, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fe327fbfe18>
                   └ <django.db.models.manager.Manager object at 0x7fe3240f1278>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-08 04:00:56.596 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1d9c05c048>
    └ <Thread(Thread-256, started daemon 139764855011072)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f1d9c05bd90>
    └ <Thread(Thread-256, started daemon 139764855011072)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-256, started daemon 139764855011072)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-256, started daemon 139764855011072)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>>
    └ <Thread(Thread-256, started daemon 139764855011072)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 58546)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f1d94ff4268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
    │    │                   │        └ ('127.0.0.1', 58546)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1d93df17b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d910d7e80>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1d93df1840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d910d7e80>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f1d93defd08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d910d7e80>
    │       └ <function BaseHandler.run at 0x7f1d93deca60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d8b126dd8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f1d93decd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d8b126dd8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d8b126dd8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d8b126dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function BaseHandler.get_response at 0x7f1d93e21f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107abf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f1d91127438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107ab70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f1d91127438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1d91127ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107aae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1d91127ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f1d91127f60>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107aa60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f1d91127f60>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f1d9112bd68>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a9d8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f1d9112bd68>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f1d91c90668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a950>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f1d91c90668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1d91c905c0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1d91c905c0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1d91c90518>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1d91c90518>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1d92857080>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a7b8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1d92857080>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1d91c7f710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1d91c7f710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1d91c7fa90>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function BaseHandler._get_response at 0x7f1d912bdf28>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1d91c7fa90>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 738}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <function doc at 0x7f1d91b3c158>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 738}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-738/'>
           └ <function doc at 0x7f1d91b3c0d0>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 738
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f1d93ef2c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 738, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f1d950aee18>
                   └ <django.db.models.manager.Manager object at 0x7f1d9119b4e0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-08 05:16:52.267 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1d9c05c048>
    └ <Thread(Thread-293, started daemon 139764874680064)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f1d9c05bd90>
    └ <Thread(Thread-293, started daemon 139764874680064)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-293, started daemon 139764874680064)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-293, started daemon 139764874680064)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>>
    └ <Thread(Thread-293, started daemon 139764874680064)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 58798)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f1d94ff4268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
    │    │                   │        └ ('127.0.0.1', 58798)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1d93df17b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d8b095f28>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1d93df1840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d8b095f28>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f1d93defd08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d8b095f28>
    │       └ <function BaseHandler.run at 0x7f1d93deca60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d9129b908>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f1d93decd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d9129b908>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d9129b908>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d9129b908>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │    └ <function BaseHandler.get_response at 0x7f1d93e21f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-778/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107abf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f1d91127438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107ab70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f1d91127438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1d91127ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107aae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1d91127ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f1d91127f60>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107aa60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f1d91127f60>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f1d9112bd68>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a9d8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f1d9112bd68>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f1d91c90668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a950>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f1d91c90668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1d91c905c0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1d91c905c0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1d91c90518>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1d91c90518>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1d92857080>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a7b8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1d92857080>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1d91c7f710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1d91c7f710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1d91c7fa90>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               │    └ <function BaseHandler._get_response at 0x7f1d912bdf28>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1d91c7fa90>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 778}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-778/'>
               └ <function doc at 0x7f1d91b3c158>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 778}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-778/'>
           └ <function doc at 0x7f1d91b3c0d0>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 778
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f1d93ef2c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 778, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f1d950aee18>
                   └ <django.db.models.manager.Manager object at 0x7f1d9119b4e0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-08 06:02:29.414 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1d9c05c048>
    └ <Thread(Thread-305, started daemon 139764874680064)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f1d9c05bd90>
    └ <Thread(Thread-305, started daemon 139764874680064)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-305, started daemon 139764874680064)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-305, started daemon 139764874680064)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>>
    └ <Thread(Thread-305, started daemon 139764874680064)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 58932)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f1d94ff4268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
    │    │                   │        └ ('127.0.0.1', 58932)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1d93df17b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d910f5630>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1d93df1840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d910f5630>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f1d93defd08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d910f5630>
    │       └ <function BaseHandler.run at 0x7f1d93deca60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d9112b5f8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f1d93decd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d9112b5f8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d9112b5f8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d9112b5f8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               │    └ <function BaseHandler.get_response at 0x7f1d93e21f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-538/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107abf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f1d91127438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107ab70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f1d91127438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1d91127ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107aae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1d91127ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f1d91127f60>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107aa60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f1d91127f60>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f1d9112bd68>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a9d8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f1d9112bd68>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f1d91c90668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a950>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f1d91c90668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1d91c905c0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1d91c905c0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1d91c90518>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1d91c90518>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1d92857080>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a7b8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1d92857080>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1d91c7f710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1d91c7f710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1d91c7fa90>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               │    └ <function BaseHandler._get_response at 0x7f1d912bdf28>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1d91c7fa90>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-538/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 538}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-538/'>
               └ <function doc at 0x7f1d91b3c158>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 538}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-538/'>
           └ <function doc at 0x7f1d91b3c0d0>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 538
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f1d93ef2c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 538, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f1d950aee18>
                   └ <django.db.models.manager.Manager object at 0x7f1d9119b4e0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-08 07:21:14.803 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1d9c05c048>
    └ <Thread(Thread-321, started daemon 139764874680064)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f1d9c05bd90>
    └ <Thread(Thread-321, started daemon 139764874680064)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-321, started daemon 139764874680064)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-321, started daemon 139764874680064)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>>
    └ <Thread(Thread-321, started daemon 139764874680064)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 59174)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f1d94ff4268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
    │    │                   │        └ ('127.0.0.1', 59174)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1d93df17b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d8a02f128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1d93df1840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d8a02f128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f1d93defd08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d8a02f128>
    │       └ <function BaseHandler.run at 0x7f1d93deca60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d8b0959e8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f1d93decd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d8b0959e8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d8b0959e8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d8b0959e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │    └ <function BaseHandler.get_response at 0x7f1d93e21f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-511/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107abf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f1d91127438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107ab70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f1d91127438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1d91127ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107aae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1d91127ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f1d91127f60>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107aa60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f1d91127f60>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f1d9112bd68>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a9d8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f1d9112bd68>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f1d91c90668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a950>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f1d91c90668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1d91c905c0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1d91c905c0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1d91c90518>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1d91c90518>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1d92857080>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a7b8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1d92857080>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1d91c7f710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1d91c7f710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1d91c7fa90>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               │    └ <function BaseHandler._get_response at 0x7f1d912bdf28>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1d91c7fa90>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 511}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-511/'>
               └ <function doc at 0x7f1d91b3c158>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 511}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-511/'>
           └ <function doc at 0x7f1d91b3c0d0>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 511
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f1d93ef2c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 511, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f1d950aee18>
                   └ <django.db.models.manager.Manager object at 0x7f1d9119b4e0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-08 13:45:11.955 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1d9c05c048>
    └ <Thread(Thread-901, started daemon 139764843472640)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f1d9c05bd90>
    └ <Thread(Thread-901, started daemon 139764843472640)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-901, started daemon 139764843472640)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-901, started daemon 139764843472640)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>>
    └ <Thread(Thread-901, started daemon 139764843472640)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 33052)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f1d94ff4268>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
    │    │                   │        └ ('127.0.0.1', 33052)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1d93df17b8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d8b10c710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1d93df1840>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d8b10c710>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f1d93defd08>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f1d954c30f0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f1d8b10c710>
    │       └ <function BaseHandler.run at 0x7f1d93deca60>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d9a1742b0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f1d93decd90>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d9a1742b0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d9a1742b0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f1d9a1742b0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function BaseHandler.get_response at 0x7f1d93e21f28>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107abf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f1d91127438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107ab70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f1d91127438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1d91127ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107aae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f1d91127ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f1d91127f60>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107aa60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f1d91127f60>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f1d9112bd68>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a9d8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f1d9112bd68>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f1d91c90668>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a950>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f1d91c90668>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1d91c905c0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f1d91c905c0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1d91c90518>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f1d91c90518>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1d92857080>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a7b8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f1d92857080>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1d91c7f710>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f1d9107a8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f1d91c7f710>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1d91c7fa90>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function BaseHandler._get_response at 0x7f1d912bdf28>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f1d91c7fa90>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f1d928c3c50>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 323}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <function doc at 0x7f1d91b3c158>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 323}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-323/'>
           └ <function doc at 0x7f1d91b3c0d0>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 323
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f1d93ef2c88>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 323, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f1d950aee18>
                   └ <django.db.models.manager.Manager object at 0x7f1d9119b4e0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
