2022-06-05 02:06:09.022 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a00d8d048>
    └ <Thread(Thread-187, started daemon 139818015909632)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a00d8cd90>
    └ <Thread(Thread-187, started daemon 139818015909632)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-187, started daemon 139818015909632)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-187, started daemon 139818015909632)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>>
    └ <Thread(Thread-187, started daemon 139818015909632)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 33738)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f29f9d2b1e0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │    │                   │        └ ('127.0.0.1', 33738)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f29f8b19f28>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29f09c0eb8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f29f8b1a048>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29f09c0eb8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f29f8b19510>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29f09c0eb8>
    │       └ <function BaseHandler.run at 0x7f29f8b13268>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29f0126438>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f29f8b13598>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f29f0126438>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f29f0126438>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29f0126438>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler.get_response at 0x7f29f8b58730>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e351e0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e350d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35048>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22f28>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22ea0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22e18>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d90>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22c80>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler._get_response at 0x7f29f81972f0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 273}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <function doc at 0x7f29f27b6378>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 273}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-273/'>
           └ <function doc at 0x7f29f27b62f0>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 273
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f29f8c20358>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 273, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f29f9de3d90>
                   └ <django.db.models.manager.Manager object at 0x7f29f81b56a0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-05 04:12:44.304 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a00d8d048>
    └ <Thread(Thread-222, started daemon 139818015909632)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a00d8cd90>
    └ <Thread(Thread-222, started daemon 139818015909632)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-222, started daemon 139818015909632)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-222, started daemon 139818015909632)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>>
    └ <Thread(Thread-222, started daemon 139818015909632)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 33886)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f29f9d2b1e0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │    │                   │        └ ('127.0.0.1', 33886)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f29f8b19f28>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29f010b0b8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f29f8b1a048>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29f010b0b8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f29f8b19510>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29f010b0b8>
    │       └ <function BaseHandler.run at 0x7f29f8b13268>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29ebe58d30>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f29f8b13598>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f29ebe58d30>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f29ebe58d30>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29ebe58d30>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │    └ <function BaseHandler.get_response at 0x7f29f8b58730>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-43/doc-775/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e351e0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e350d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35048>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22f28>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22ea0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22e18>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d90>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22c80>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               │    └ <function BaseHandler._get_response at 0x7f29f81972f0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 43, 'doc_id': 775}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-43/doc-775/'>
               └ <function doc at 0x7f29f27b6378>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 43, 'doc_id': 775}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-43/doc-775/'>
           └ <function doc at 0x7f29f27b62f0>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 775
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f29f8c20358>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 775, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f29f9de3d90>
                   └ <django.db.models.manager.Manager object at 0x7f29f81b56a0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-05 09:06:55.116 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a00d8d048>
    └ <Thread(Thread-285, started daemon 139818015909632)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a00d8cd90>
    └ <Thread(Thread-285, started daemon 139818015909632)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-285, started daemon 139818015909632)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-285, started daemon 139818015909632)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>>
    └ <Thread(Thread-285, started daemon 139818015909632)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 34148)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f29f9d2b1e0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │    │                   │        └ ('127.0.0.1', 34148)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f29f8b19f28>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29ebd78358>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f29f8b1a048>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29ebd78358>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f29f8b19510>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29ebd78358>
    │       └ <function BaseHandler.run at 0x7f29f8b13268>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29ebfccef0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f29f8b13598>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f29ebfccef0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f29ebfccef0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29ebfccef0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               │    └ <function BaseHandler.get_response at 0x7f29f8b58730>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-10/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e351e0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e350d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35048>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22f28>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22ea0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22e18>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d90>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22c80>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               │    └ <function BaseHandler._get_response at 0x7f29f81972f0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-10/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 10}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-10/'>
               └ <function doc at 0x7f29f27b6378>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 10}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-10/'>
           └ <function doc at 0x7f29f27b62f0>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 10
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f29f8c20358>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 10, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f29f9de3d90>
                   └ <django.db.models.manager.Manager object at 0x7f29f81b56a0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-05 11:56:02.019 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a00d8d048>
    └ <Thread(Thread-591, started daemon 139818106582784)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a00d8cd90>
    └ <Thread(Thread-591, started daemon 139818106582784)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-591, started daemon 139818106582784)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-591, started daemon 139818106582784)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>>
    └ <Thread(Thread-591, started daemon 139818106582784)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 34848)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f29f9d2b1e0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │    │                   │        └ ('127.0.0.1', 34848)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f29f8b19f28>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29ebe01748>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f29f8b1a048>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29ebe01748>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f29f8b19510>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29ebe01748>
    │       └ <function BaseHandler.run at 0x7f29f8b13268>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb499cc0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f29f8b13598>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb499cc0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb499cc0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb499cc0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │    └ <function BaseHandler.get_response at 0x7f29f8b58730>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-292/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e351e0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e350d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35048>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22f28>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22ea0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22e18>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d90>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22c80>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               │    └ <function BaseHandler._get_response at 0x7f29f81972f0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 292}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-292/'>
               └ <function doc at 0x7f29f27b6378>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 292}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-292/'>
           └ <function doc at 0x7f29f27b62f0>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 292
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f29f8c20358>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 292, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f29f9de3d90>
                   └ <django.db.models.manager.Manager object at 0x7f29f81b56a0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-05 12:02:56.244 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a00d8d048>
    └ <Thread(Thread-611, started daemon 139818106582784)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a00d8cd90>
    └ <Thread(Thread-611, started daemon 139818106582784)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-611, started daemon 139818106582784)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-611, started daemon 139818106582784)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>>
    └ <Thread(Thread-611, started daemon 139818106582784)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 34894)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f29f9d2b1e0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │    │                   │        └ ('127.0.0.1', 34894)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f29f8b19f28>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29f818d630>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f29f8b1a048>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29f818d630>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f29f8b19510>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29f818d630>
    │       └ <function BaseHandler.run at 0x7f29f8b13268>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb531668>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f29f8b13598>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb531668>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb531668>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb531668>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler.get_response at 0x7f29f8b58730>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e351e0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e350d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35048>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22f28>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22ea0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22e18>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d90>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22c80>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler._get_response at 0x7f29f81972f0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 273}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <function doc at 0x7f29f27b6378>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 273}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-273/'>
           └ <function doc at 0x7f29f27b62f0>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 273
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f29f8c20358>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 273, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f29f9de3d90>
                   └ <django.db.models.manager.Manager object at 0x7f29f81b56a0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-05 12:08:01.538 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a00d8d048>
    └ <Thread(Thread-625, started daemon 139818106582784)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a00d8cd90>
    └ <Thread(Thread-625, started daemon 139818106582784)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-625, started daemon 139818106582784)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-625, started daemon 139818106582784)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>>
    └ <Thread(Thread-625, started daemon 139818106582784)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 34922)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f29f9d2b1e0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │    │                   │        └ ('127.0.0.1', 34922)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f29f8b19f28>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29eb491e10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f29f8b1a048>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29eb491e10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f29f8b19510>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29eb491e10>
    │       └ <function BaseHandler.run at 0x7f29f8b13268>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb527400>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f29f8b13598>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb527400>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb527400>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb527400>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function BaseHandler.get_response at 0x7f29f8b58730>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e351e0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e350d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35048>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22f28>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22ea0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22e18>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d90>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22c80>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function BaseHandler._get_response at 0x7f29f81972f0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 343}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <function doc at 0x7f29f27b6378>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 343}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-343/'>
           └ <function doc at 0x7f29f27b62f0>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 343
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f29f8c20358>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 343, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f29f9de3d90>
                   └ <django.db.models.manager.Manager object at 0x7f29f81b56a0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-06-05 12:11:42.004 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f2a00d8d048>
    └ <Thread(Thread-637, started daemon 139818106582784)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f2a00d8cd90>
    └ <Thread(Thread-637, started daemon 139818106582784)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-637, started daemon 139818106582784)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-637, started daemon 139818106582784)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>>
    └ <Thread(Thread-637, started daemon 139818106582784)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 34948)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f29f9d2b1e0>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │    │                   │        └ ('127.0.0.1', 34948)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f29f8b19f28>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29eb46be10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f29f8b1a048>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29eb46be10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f29f8b19510>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f29fa479eb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f29eb46be10>
    │       └ <function BaseHandler.run at 0x7f29f8b13268>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb456828>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f29f8b13598>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb456828>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb456828>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f29eb456828>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function BaseHandler.get_response at 0x7f29f8b58730>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e351e0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f29f1e4e780>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e350d0>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f29f1e4ebe0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e35048>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f29f1e5ce80>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22f28>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f29f1e5c438>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22ea0>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f29f2b99208>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22e18>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f29f2b99ef0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d90>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f29f2b99e48>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f29f2b99dd8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f29f1e22c80>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f29f1e68860>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function BaseHandler._get_response at 0x7f29f81972f0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f29f1e68ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f29f3599518>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 738}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <function doc at 0x7f29f27b6378>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 738}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-738/'>
           └ <function doc at 0x7f29f27b62f0>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 738
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f29f8c20358>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 738, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f29f9de3d90>
                   └ <django.db.models.manager.Manager object at 0x7f29f81b56a0>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
