2022-07-18 20:30:55.500 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6522bfdea0>
    └ <Thread(Thread-1873, started daemon 140071835531008)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6522bfdc80>
    └ <Thread(Thread-1873, started daemon 140071835531008)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1873, started daemon 140071835531008)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1873, started daemon 140071835531008)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>>
    └ <Thread(Thread-1873, started daemon 140071835531008)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60944)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f651bb97158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │    │                   │        └ ('127.0.0.1', 60944)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f651a9956a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f651277c198>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f651a995730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f651277c198>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f651a991bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f651277c198>
    │       └ <function BaseHandler.run at 0x7f651a98d950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511bd0c18>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f651a98dc80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511bd0c18>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511bd0c18>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511bd0c18>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               │    └ <function BaseHandler.get_response at 0x7f651a9c5e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-540/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15ae8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15a60>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c159d8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15950>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c158c8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c157b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d90>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               │    └ <function BaseHandler._get_response at 0x7f651ce3ba60>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-540/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 540}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-540/'>
               └ <function doc at 0x7f65186f7048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 540}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-540/'>
           └ <function doc at 0x7f65186f3f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 540
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f651aa95ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 540, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f651bc50d08>
                   └ <django.db.models.manager.Manager object at 0x7f651a13c438>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-18 21:07:07.429 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6522bfdea0>
    └ <Thread(Thread-1923, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6522bfdc80>
    └ <Thread(Thread-1923, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1923, started daemon 140072065697536)>
    │    │        │    └ (<socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1923, started daemon 140072065697536)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>>
    └ <Thread(Thread-1923, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 32900)
    │    │              └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f651bb97158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │    │                   │        └ ('127.0.0.1', 32900)
    │    │                   └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f651a9956a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f65000a9e10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f651a995730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f65000a9e10>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f651a991bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f65000a9e10>
    │       └ <function BaseHandler.run at 0x7f651a98d950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511b871d0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f651a98dc80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511b871d0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511b871d0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511b871d0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function BaseHandler.get_response at 0x7f651a9c5e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15ae8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15a60>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c159d8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15950>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c158c8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c157b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d90>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               │    └ <function BaseHandler._get_response at 0x7f651ce3ba60>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 738}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-738/'>
               └ <function doc at 0x7f65186f7048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 738}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-738/'>
           └ <function doc at 0x7f65186f3f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 738
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f651aa95ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 738, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f651bc50d08>
                   └ <django.db.models.manager.Manager object at 0x7f651a13c438>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-18 22:30:27.032 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6522bfdea0>
    └ <Thread(Thread-1946, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6522bfdc80>
    └ <Thread(Thread-1946, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1946, started daemon 140072065697536)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1946, started daemon 140072065697536)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>>
    └ <Thread(Thread-1946, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 33182)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f651bb97158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │    │                   │        └ ('127.0.0.1', 33182)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f651a9956a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f6511361be0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f651a995730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f6511361be0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f651a991bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f6511361be0>
    │       └ <function BaseHandler.run at 0x7f651a98d950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f65112a6048>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f651a98dc80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f65112a6048>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f65112a6048>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f65112a6048>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │    └ <function BaseHandler.get_response at 0x7f651a9c5e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-524/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15ae8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15a60>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c159d8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15950>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c158c8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c157b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d90>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │    └ <function BaseHandler._get_response at 0x7f651ce3ba60>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 524}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <function doc at 0x7f65186f7048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 524}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-524/'>
           └ <function doc at 0x7f65186f3f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 524
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f651aa95ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 524, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f651bc50d08>
                   └ <django.db.models.manager.Manager object at 0x7f651a13c438>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-19 01:53:16.279 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6522bfdea0>
    └ <Thread(Thread-2014, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6522bfdc80>
    └ <Thread(Thread-2014, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2014, started daemon 140072065697536)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2014, started daemon 140072065697536)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>>
    └ <Thread(Thread-2014, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 33820)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f651bb97158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │    │                   │        └ ('127.0.0.1', 33820)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f651a9956a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f6511cb6128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f651a995730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f6511cb6128>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f651a991bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f6511cb6128>
    │       └ <function BaseHandler.run at 0x7f651a98d950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f65112bc1d0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f651a98dc80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f65112bc1d0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f65112bc1d0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f65112bc1d0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function BaseHandler.get_response at 0x7f651a9c5e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15ae8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15a60>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c159d8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15950>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c158c8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c157b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d90>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               │    └ <function BaseHandler._get_response at 0x7f651ce3ba60>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 26, 'doc_id': 306}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-26/doc-306/'>
               └ <function doc at 0x7f65186f7048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 26, 'doc_id': 306}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-26/doc-306/'>
           └ <function doc at 0x7f65186f3f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 306
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f651aa95ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 306, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f651bc50d08>
                   └ <django.db.models.manager.Manager object at 0x7f651a13c438>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-19 03:19:26.776 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6522bfdea0>
    └ <Thread(Thread-2030, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6522bfdc80>
    └ <Thread(Thread-2030, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2030, started daemon 140072065697536)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2030, started daemon 140072065697536)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>>
    └ <Thread(Thread-2030, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 34050)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f651bb97158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │    │                   │        └ ('127.0.0.1', 34050)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f651a9956a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f65112d70f0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f651a995730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f65112d70f0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f651a991bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f65112d70f0>
    │       └ <function BaseHandler.run at 0x7f651a98d950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511cc5d68>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f651a98dc80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511cc5d68>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511cc5d68>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511cc5d68>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │    └ <function BaseHandler.get_response at 0x7f651a9c5e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-344/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15ae8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15a60>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c159d8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15950>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c158c8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c157b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d90>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               │    └ <function BaseHandler._get_response at 0x7f651ce3ba60>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 344}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-344/'>
               └ <function doc at 0x7f65186f7048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 344}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-344/'>
           └ <function doc at 0x7f65186f3f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 344
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f651aa95ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 344, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f651bc50d08>
                   └ <django.db.models.manager.Manager object at 0x7f651a13c438>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-19 03:23:17.472 | ERROR    | app_doc.views:doc:1075 - 文集浏览出错
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6522bfdea0>
    └ <Thread(Thread-2032, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6522bfdc80>
    └ <Thread(Thread-2032, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2032, started daemon 140072065697536)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2032, started daemon 140072065697536)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>>
    └ <Thread(Thread-2032, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 34064)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f651bb97158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │    │                   │        └ ('127.0.0.1', 34064)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f651a9956a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f651ce29550>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f651a995730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f651ce29550>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f651a991bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f651ce29550>
    │       └ <function BaseHandler.run at 0x7f651a98d950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f651130efd0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f651a98dc80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f651130efd0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f651130efd0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f651130efd0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               │    └ <function BaseHandler.get_response at 0x7f651a9c5e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-279/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15ae8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15a60>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c159d8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15950>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c158c8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c157b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d90>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               │    └ <function BaseHandler._get_response at 0x7f651ce3ba60>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-279/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 279}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-279/'>
               └ <function doc at 0x7f65186f7048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 279}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-279/'>
           └ <function doc at 0x7f65186f3f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 279
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f651aa95ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 279, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f651bc50d08>
                   └ <django.db.models.manager.Manager object at 0x7f651a13c438>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-19 07:00:12.204 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6522bfdea0>
    └ <Thread(Thread-2173, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6522bfdc80>
    └ <Thread(Thread-2173, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2173, started daemon 140072065697536)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2173, started daemon 140072065697536)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>>
    └ <Thread(Thread-2173, started daemon 140072065697536)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 34892)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f651bb97158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │    │                   │        └ ('127.0.0.1', 34892)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f651a9956a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f651277c198>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f651a995730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f651277c198>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f651a991bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f651277c198>
    │       └ <function BaseHandler.run at 0x7f651a98d950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f65112c8b38>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f651a98dc80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f65112c8b38>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f65112c8b38>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f65112c8b38>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler.get_response at 0x7f651a9c5e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15ae8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15a60>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c159d8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15950>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c158c8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c157b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d90>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               │    └ <function BaseHandler._get_response at 0x7f651ce3ba60>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 273}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-273/'>
               └ <function doc at 0x7f65186f7048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 273}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-273/'>
           └ <function doc at 0x7f65186f3f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 273
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f651aa95ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 273, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f651bc50d08>
                   └ <django.db.models.manager.Manager object at 0x7f651a13c438>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-19 09:36:56.122 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6522bfdea0>
    └ <Thread(Thread-2292, started daemon 140071835531008)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6522bfdc80>
    └ <Thread(Thread-2292, started daemon 140071835531008)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2292, started daemon 140071835531008)>
    │    │        │    └ (<socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2292, started daemon 140071835531008)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>>
    └ <Thread(Thread-2292, started daemon 140071835531008)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 35532)
    │    │              └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f651bb97158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │    │                   │        └ ('127.0.0.1', 35532)
    │    │                   └ <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f651a9956a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f6512779fd0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f651a995730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f6512779fd0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f651a991bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f6512779fd0>
    │       └ <function BaseHandler.run at 0x7f651a98d950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511c95cf8>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f651a98dc80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511c95cf8>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511c95cf8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511c95cf8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               │    └ <function BaseHandler.get_response at 0x7f651a9c5e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-539/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15ae8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15a60>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c159d8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15950>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c158c8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c157b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d90>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               │    └ <function BaseHandler._get_response at 0x7f651ce3ba60>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-539/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 539}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-539/'>
               └ <function doc at 0x7f65186f7048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 539}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-539/'>
           └ <function doc at 0x7f65186f3f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 539
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f651aa95ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 539, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f651bc50d08>
                   └ <django.db.models.manager.Manager object at 0x7f651a13c438>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-19 11:34:30.832 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6522bfdea0>
    └ <Thread(Thread-2831, started daemon 140072048912128)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6522bfdc80>
    └ <Thread(Thread-2831, started daemon 140072048912128)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2831, started daemon 140072048912128)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2831, started daemon 140072048912128)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>>
    └ <Thread(Thread-2831, started daemon 140072048912128)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 38760)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f651bb97158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │    │                   │        └ ('127.0.0.1', 38760)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f651a9956a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f651129f978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f651a995730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f651129f978>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f651a991bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f651129f978>
    │       └ <function BaseHandler.run at 0x7f651a98d950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f651277c198>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f651a98dc80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f651277c198>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f651277c198>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f651277c198>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               │    └ <function BaseHandler.get_response at 0x7f651a9c5e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-518/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15ae8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15a60>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c159d8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15950>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c158c8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c157b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d90>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               │    └ <function BaseHandler._get_response at 0x7f651ce3ba60>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-518/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 518}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-518/'>
               └ <function doc at 0x7f65186f7048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 518}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-518/'>
           └ <function doc at 0x7f65186f3f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 518
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f651aa95ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 518, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f651bc50d08>
                   └ <django.db.models.manager.Manager object at 0x7f651a13c438>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-07-19 11:34:32.987 | ERROR    | app_doc.views:doc:1075 - Collection browsing error
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 887, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6522bfdea0>
    └ <Thread(Thread-2832, started daemon 140072048912128)>
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6522bfdc80>
    └ <Thread(Thread-2832, started daemon 140072048912128)>
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2832, started daemon 140072048912128)>
    │    │        │    └ (<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-2832, started daemon 140072048912128)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>>
    └ <Thread(Thread-2832, started daemon 140072048912128)>
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 38762)
    │    │              └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f651bb97158>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │    │                   │        └ ('127.0.0.1', 38762)
    │    │                   └ <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f651a9956a8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f6511288b00>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f651a995730>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f6511288b00>

  File "/usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f651a991bf8>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f651c2e7fd0>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f6511288b00>
    │       └ <function BaseHandler.run at 0x7f651a98d950>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511bcdbe0>

  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f651a98dc80>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511bcdbe0>
    │    │        │           │    └ {'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511bcdbe0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f6511bcdbe0>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │    └ <function BaseHandler.get_response at 0x7f651a9c5e18>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-34/doc-524/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15ae8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15a60>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f6513c43470>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c159d8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f6513c437f0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15950>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f6513c43898>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c158c8>
               │           └ <corsheaders.middleware.CorsMiddleware object at 0x7f6513c50a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c157b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f6513c502b0>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15730>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f6518845ac8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c15840>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f6518845ba8>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d08>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f6518845b00>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>

  File "/usr/local/lib64/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f6513c77d90>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f6518845a90>
               └ None

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 36, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               │    └ <function BaseHandler._get_response at 0x7f651ce3ba60>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f65194099e8>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f6518831f98>>

  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 34, 'doc_id': 524}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-34/doc-524/'>
               └ <function doc at 0x7f65186f7048>

  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 34, 'doc_id': 524}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-34/doc-524/'>
           └ <function doc at 0x7f65186f3f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1002, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 524
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f651aa95ba8>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 524, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f651bc50d08>
                   └ <django.db.models.manager.Manager object at 0x7f651a13c438>

  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 算法框架>, <Doc: TDH>, <Doc: 常用方法>, <Doc: Shell>, <Doc: 常用命令>, <Doc: 示例脚本>, <Doc: Redis>, <Doc: 常用...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
